### ISSUE TITLE
A search that returns no records causes unexpected behavior

### ISSUE THREAD

**Issue by RobertBruening** [opensalt/opensalt#1006]
**Thank you for your interest in OpenSALT!**

> This template helps ensure that we have enough information to work on
> the issue.<br/>
> Please feel free to ignore any section that is not applicable or add
> additional information.

### Describe the problem
Search for something that will return no records. Observe that 
1) Whatever standards are on the list stay there.
2) The standards disappear from the list view when clicked on 
### Version of OpenSALT
The version of OpenSALT you are working on (select _About OpenSALT_ at the bottom right of the page)
OpenSALT™ 2.2.0.1990+20190627.1947.7c6e5e2d
Also, whatever version the CASE network is using...no "About OpenSALT" to select

### To reproduce
Steps to reproduce the behaviour:
1. Go to 'https://case.georgiastandards.org/cftree/doc/402'
2. Enter 'abcdefg' in the search bar
3. See that nothing changes
4. Click on a standard
5. See that the standard is removed from the list

### Expected behaviour
1) The search causes all standards to be filtered
2) If not 1) the standards at least don't disappear when clicked
### Actual behaviour
1) no standards are filtered
2) the standards disappear when clicked 
### Screenshots
![image](https://user-images.githubusercontent.com/40371368/73761812-f73c0a00-4734-11ea-8f7c-3802d1f4fa38.png)

![image](https://user-images.githubusercontent.com/40371368/73761879-0ae77080-4735-11ea-8eb3-d2feb30aa6c3.png)

### Your system (please complete the following information):
 - Device: desktop
 - OS: Windows 10
 - Browser Chrome 
 - Version: 79.0.3945.130 

#### If you are able to report the URL where an error happened or output from the dev console please do so.

 https://case.georgiastandards.org/cftree/doc/402
site.3e4db06c.js:34 Uncaught TypeError: Cannot read property 'title' of undefined
    at b.renderNode (site.3e4db06c.js:34)
    at b.nodeRender (base.bd134095.js:1)
    at b._callHook (base.bd134095.js:1)
    at y.render (base.bd134095.js:1)
    at y.addChildren (base.bd134095.js:1)
    at y.addNode (base.bd134095.js:1)
    at b.e.ui.fancytree._FancytreeClass._applyFilterImpl (base.bd134095.js:1)
    at b.e.ui.fancytree._FancytreeClass.filterNodes (base.bd134095.js:1)
    at site.3e4db06c.js:34
### Additional acceptance criteria tests
```gherkin
Scenario:  
Given 
When 
Then 
```

**Comment by roverwolf** [comment]
@RobertBruening Thank you for the bug report.

We will be looking at fixing the issue for the next version of OpenSALT.
