### ISSUE TITLE
WYSIWYG editing for item fullStatement and still store as CASE-compliant text

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#106]
Add WYSIWYG editor to item editing of the **fullStatement** field.

Save text in **Markdown** format.

- [ ] #170 Render fullStatement from Markdown

**Comment by roverwolf** [comment]
Questions:
  - Which text fields are we talking about?
    - FullStatement only?
    - Others?
  - The spec and implementation guide both state that the content should be plain text.
    - What WYSIWYG styles are we wanting, and what "CASE-compiiant formatting" are we considering?
        - Possibly using a flavour of Markdown?

**Comment by brandonopened** [comment]
Fields: FullStatement for sure
- Suggesting markdown because while it wouldn't look good in tools other than OpenSALT, it would still be readable unlike HTML.

**Comment by jmarks** [comment]
Some notes on the approach: I think only full statement, and you can choose from an an extensible list of encoding (Mark down being the first and default to enable tables.) HTML, MathML or other mark-up editors can be supported as extensions. When an item full statement is encoded in from mark-up, it shoudl have a type header applied as well.

**Comment by roverwolf** [comment]
@jmarks The problem with other marksup (HTML, MathML, ...) is that they are against the CASE specification and do not present well (or at all) with "text-only".

Section [6.2](https://www.imsglobal.org/sites/default/files/CASE/casev1p0/best_practices/caseservicev1p0_bestpracticesv1p0.html#OtherBestPractices_2) of the best practices guide specifically states:

> fullStatement
>> UTF8
>> in version 1 of the CF spec, **markup is not supported** in order to assure greater interoperability

**Comment by jmarks** [comment]
Ok, we can avoid Markup for now, but eventually may need it. Here are some user storied, and we can fit the implementation to them. Please review and revise:

1) As an editor I want to create or edit an item that has formatted text (Bold, Ital, Strike though and Underline), math symbols and equations in the the rendered item view for full statement, short statement and notes, by typing markdown, LaTeX or pasting math content from Microsoft Word or PDF. Pasting can convert format and encoding. I also want to see what it will look like before I save (real time render view or WYSIWYG editor)

2) As an editor I want to create of edit an item that has a formatted table in the the rendered item view for full statement and notes by typing markdown, LaTeX or pasting a table for formatted content from HTML, Microsoft Word or PDF. Pasting can convert format and encoding.

3)  As an editor creating or editing an item or document, if I enter any text that is not supported, I shoudl get a validation error on saving

4) As an editor, if I am entering markdown, LaTeX I have access to a reference guide on how to input correct math, tables and formatted text or have a WYSIWYG editor to input the text correctly.

**Comment by roverwolf** [comment]
@jmarks Questions/Comments:

1. Formatting
a) Should the "short statement" allow for markdown/LaTeX?
b) I don't think "convert format and encoding" from Word, etc. is feasible here.

2. Tables
a) I don't think pasting from HTML, Word, PDF is feasible here.

3. Vadlidation
a) What do we mean here by "is not supported'?

4. Reference Guide
a) Is this mean to be a selectable link to show the various syntax available?

**Comment by jmarks** [comment]
@roverwolf answers inline below:

Questions/Comments:

Formatting
a) Should the "short statement" allow for markdown/LaTeX?

JM>Yes as it might include a Math formula or styled text. However, no tables or perhaps even line break in short statement seems important. 

b) I don't think "convert format and encoding" from Word, etc. is feasible here.

JM> What if anything can be done here. There will be LOTs of copy and paste from Word, PDF and HTML documents, and formatting and tables are a big part of that content. Re entering tables and formatting will be very problematic for framework editors converting form documents. Paste table and styles text is the most important, Math can be re-entered if not available in Markdown/LaTe source. 

Tables
a) I don't think pasting from HTML, Word, PDF is feasible here.

JM> This is perhaps most important. Is there no HTML to Markdown table translator? I know there are other WIki Syntax "Paste from" tools in some of the WYSIWYG editors. The tables below are pasted from different sources to show how GitHub MarkDown Deals with this. It seems the editor JS they use converts tables reasonably::

**(2x3 table from Google Sheet copy and paste)**

Sept | Oct
-- | --
text | More Text
Some Text | Some more text


**(Excel)**

Sept | Oct
-- | --
text | More   Text
Some   Text | Some   more text

**(Word)**

Sept | Oct
-- | --
text | More Text
Some Text | Some more text

**(from HTML)**

Company | Contact | Country
-- | -- | --
Alfreds Futterkiste | Maria Anders | Germany
Centro comercial Moctezuma | Francisco Chang | Mexico
Ernst Handel | Roland Mendel | Austria
Island Trading | Helen Bennett | UK
Laughing Bacchus Winecellars | Yoshi Tannamuri | Canada
Magazzini Alimentari Riuniti | Giovanni Rovelli | Italy



Validation
a) What do we mean here by "is not supported'?

JM> Basic error handling if the data has an issue, such as the our of range UTF8 characters we saw in Georgia. 

Reference Guide
a) Is this mean to be a selectable link to show the various syntax available?

> Exactly, so I know what to type for an integral, or anything else not support with the WYSIWYG directly (e.g. equation editing, tables, etc.) (See the Github editor link as a model)

**Comment by jmarks** [comment]
Interestingly, tables from a PDF do not copy. Here is an example:

An image of the PDF table:
![image](https://user-images.githubusercontent.com/1319413/31194763-044f6b3e-a8fd-11e7-8566-92750f7d8683.png)

And the copied text from the PDF pasted here:

Example Stem 2: This table shows a proportional relationship between the number of cups of sugar and flour used for a recipe.
Cups of Sugar
Cups of Flour
212
712
334
1114
Enter the number of cups of sugar used for 1 cup of flour.

**Comment by jmarks** [comment]
On testing, auto linking should be turned off. See: https://salt-dev.edplancms.com/cftree/item/143369 note the test "3.MD" looks like a link when it shoudl not.

**Comment by jmarks** [comment]
fixes and improvements to WYSIWYG:
1) Full screen needs to go bigger then dialog box (Fix)
2) Save button on full screen and side-by-side (improvement)
3) Word paste or import and convert (Extension)
4) File upload and insert for 1.4 story (Extension in 1.4)
5) UTF8 Character picker in WYSIWYG (Extension)
6) Save and continue editing option, or even auto save option- (extension)
7) Underline needed for Smarter Balanced

**Comment by roverwolf** [comment]
@jmarks Please add issues for each of the improvements for priorization and scheduling.
