### ISSUE TITLE
LsDoc statusStart and statusEnd are overly constrained when using Symfony 5

### ISSUE THREAD

**Issue by sacarr** [opensalt/opensalt#1089]
**Thank you for your interest in OpenSALT!**

### Describe the problem
OpenSalt/src/Entity/Framework/LsDoc.php uses Symfony validations that are not supported for Symfony 5.  When a Framework is Imported from Excel with statusStart and statusEnd set to valid values, the Framework cannot be saved after editing.

### Version of OpenSALT
OpenSALT™ 2.3.0-dev

### To reproduce
1. Download the CVS import template from https://github.com/opensalt/opensalt/blob/develop/docs/sample%20files/spreadsheet_import_template.xlsx
2. Populate the CF Doc worksheet with test data
* Column 01, Identifier, enter 63c2b7d0-cd69-4e8a-9761-c90623104b8c
* Column 02, creator, enter 'Test Creator'
* Column 03, title, enter 'Test Framework'
* Column 04, lastChangeDate, enter '2020-06-09 00:00:00.000000+04'
* Column 05, officialSourceURL, leave blank
* Column 06, publisher, enter 'Test Publisher, LLC'
* Column 07, description, enter 'Test framework'
* Column 08, subject, enter 'Test subject'
* Column 09, language, enter 'eng'
* Column 10, version, enter '1.0.0-2020'
* Column 11, adoptionStatus, enter 'Private Draft'
* Column 12, statusStartDate, enter '2020-01-01'
* Column 13, statusEndDate, enter '2020-12-31'
* Columns 14, 15 and 15, leave blank
3. Save the template as testframework.xlsx
4. Navigate to the Opensalt landing page
5. Login as admin
6. Click the Import framework button
7. Select the Import Spreadsheet file tab
8.  Click the Choose File button
9. Navigate in the file browser to testFramework.xlsx
10. Click open
11. Click the button labelled 'Import Framework'
12. On success, expand the 'Test Creator' row
13. Click the 'Test Framework' link
14. Click the button labelled 'Edit'
15. A modal dialog is displayed. Change the value of version from 1.0.0-2020 to 1.0.1-2020 then click the button labelled 'Save Changes'
16.  Observe the form labels for the fields 'Status Start and Status End are displayed in red and decorated with an error message stating "! This value should be of type string."

### Expected behaviour
When a Framework is saved after editing and inputting valid values, the changes should be saved to the database and the Framework Item Details displayed.

### Actual behaviour
Validation errors for the status start and status end fields make it impossible to save changes to a framework.

### Screenshots
n/a

### Your system (please complete the following information):
 - Device: Macbook Pro mid-2015
 - OS: Mac OS 10.15.5
 - Browser Chrome
 - Version 83.0.4103.97 (Official Build) (64-bit)

### Additional acceptance criteria tests
```gherkin
Scenario: Edit an imported framework with valid status start and end values  
Given A framework is successfully imported from an Excel workbook
And the framework is visible
And the Edit Framework dialog is visible
And one or more valid changes have been input
When The Save Changes button is clicked the changes are saved
And the Framework Item Details is displayed
```

### Additional context

Per https://github.com/symfony/symfony/pull/31679, Date validation is no longer supported. 

After removing the @Assert/Date() annotation from statusStart and statusEnd in src/Entity/Framework/LsDoc.php (lines 244 and 257) the Edit action functions as expected.

**Comment by roverwolf** [comment]
Thank you for your detailed error report.

The removal of the assertions in `LsDoc` and `LsItem` were missed in the migration to Symfony 5.  This will be corrected soon.

**Comment by sacarr** [comment]
@roverwolf, Just a thought, perhaps the import commands should re-use the form validations?
