### ISSUE TITLE
Strange footer behavior in Internet Explorer

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#114]

**Comment by brandonopened** [comment]
![pasted image at 2017_08_17_10_34 am](https://user-images.githubusercontent.com/14943151/29887091-29675dac-8d71-11e7-801e-193ad9904cd9.png)

**Comment by brandonopened** [comment]
![image 1 1](https://user-images.githubusercontent.com/14943151/29887106-36107a70-8d71-11e7-9a8f-4182b8c954d4.png)

**Comment by brandonopened** [comment]
Was this fixed? Was not able to reproduce this morning on a Windows + IE machine. @jmarks ?

**Comment by roverwolf** [comment]
@brandonopened I was still able to reproduce it today.

I've added a PR with a fix.
