### ISSUE TITLE
Copy all items from a framework duplicates all child items.

### ISSUE THREAD

**Issue by scubajanet** [opensalt/opensalt#116]
When a user copies all items form a framework and drags them to the working framework, the application copies all parents and children and duplicates all children.

**Comment by jmarks** [comment]
From Bryan Cox at GADOE, when copying a tree of items, the top level item is renamed "Copy of..." and shoudl not. It should have the same name as the copied item.

**Comment by brandonopened** [comment]
Probably related to #146

**Comment by brandonopened** [comment]
This happens when Select All is selected.

**Comment by peppersc** [comment]
I've checked in a fix for this issue in the peppersc6 branch.
