### ISSUE TITLE
Composer 2 error

### ISSUE THREAD

**Issue by labratm** [opensalt/opensalt#1203]
### Describe the problem
When running "make force-build" i receive an error

### Version of OpenSALT
I have tried with 2.2 release and latest dev

### To reproduce
Step 5 of the install guide here: https://github.com/opensalt/opensalt/wiki/Installing-OpenSALT

### Actual behaviour
This is the error i receive
touch -c composer.lock
touch -c yarn.lock
bin/composer install --no-interaction
Creating cftf_composer_run ... done
The "codeception/c3" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - codeception/c3 is locked to version 2.5.0 and an update of this package was not requested.
    - codeception/c3 2.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
make: *** [Makefile:52: vendor] Error 2

### Your system (please complete the following information):
 - OS: Ubuntu Server 20.04.1 (also tried with 18.04.5)

Thank you in advance for any help you can provide with this install.

**Comment by roverwolf** [comment]
@labratm Sorry about the issue in building develop, some things are currently being migrated (slowly).  A fix has been added in #1204 and will be merged into develop soon.

This issue should not have appeared in the 2.2 version as it should not be trying to use composer v2 at all.

**Comment by labratm** [comment]
Thanks for fixing this so fast! Its working great now. I must have encountered a different error on 2.2. BTW, there's a typo in the wiki at the very bottom of this page: https://github.com/opensalt/opensalt/wiki/Installing-OpenSALT
It says super-admin and it should say super-user.
Thanks again.

**Comment by roverwolf** [comment]
@labratm I'm glad it is working for you now.  I'm sorry about the state it was in, we've tried to ensure the develop branch is always in a generally usable condition but sometimes things slip through and are not discovered until the next time we have some time to work on OpenSALT.

I hae also fixed the issue in the wiki that you pointed out.  Thank you for that!
