### ISSUE TITLE
Unable to submit comments 

### ISSUE THREAD

**Issue by scorpsteals** [opensalt/opensalt#1207]
### Describe the problem
Unable to submit comments. 

### Version of OpenSALT
OpenSALT™ 2.2.0.1990+20190627.1947.7c6e5e2d

### To reproduce
Steps to reproduce the behaviour:
1. Click on any node and try to submit a comment
2. Nothing happens. Open developer tools console to see error

### Expected behaviour
The comment should get submitted and displayed.

### Actual behaviour
Nothing happens the comment is not saved.

### Screenshots
![image](https://user-images.githubusercontent.com/2992160/101396011-b81c9f00-3898-11eb-9fe9-c802faeb7d93.png)

### Your system (please complete the following information):
 - Device: desktop
 - OS: WIndows 10
 - Browser Chrome
 - Version 87.0.4280.88 

#### If you are able to report the URL where an error happened or output from the dev console please do so.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by jmarks** [comment]
Appears fixed.

**Comment by roverwolf** [comment]
@jmarks It is fixed in the develop/3.x branch.  It has not been evaluated or fixed for the 2.2 release branch.

**Comment by jmarks** [comment]
Fixed

**Comment by jmarks** [comment]
Note: No plan to back port the fix to 2.2
