### ISSUE TITLE
when making associations/copy, remove or move commenting

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#129]
This looks bad - there shouldn't be commenting showing up when those tabs are selected

**Comment by brandonopened** [comment]
<img width="700" alt="screen shot 2017-09-14 at 1 56 34 pm" src="https://user-images.githubusercontent.com/14943151/30455400-a3258080-9954-11e7-84a5-062071dd752f.png">

**Comment by brandonopened** [comment]
@JorgeLu1s , once you are able to start working on this on Monday please mark in progress.

**Comment by roverwolf** [comment]
Jorge's fix has now been merged.

Linking to #112
