### ISSUE TITLE
Add expand all and collapse all to the tree views

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#135]
Need some input on how to do this? 

How about we shorten the search bar and put a button that says expand/collapse all? 

OR introduce a new user action - right clicks? 

<img width="706" alt="screen shot 2018-03-26 at 12 10 00 pm" src="https://user-images.githubusercontent.com/14943151/37927448-fd66e890-30ee-11e8-86d4-74d4bbde3655.png">

**Comment by BarbAllen** [comment]
I like mouse right-click.

**Comment by jmarks** [comment]
Expand all might be rather huge. Not sure that is something people need/want to do. Expand section maybe. Regarding right click, not in the browser and not on a phone or tablet/touch device.

**Comment by brandonopened** [comment]
I knew there was a reason we hadn't implemented those actions... Ok. Will keep this idea in the icebox. (Looking for more non-dependent things to do while we wait for file storage info from ACT regarding an S3 bucket)

**Comment by brandonopened** [comment]
Unnecessary.
