### ISSUE TITLE
SmartlLevel on Export drops the last decimal place

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#140]
When a spreadsheet is exported, when the SMartlevels go past 10 can you force the spreadsheet to keep the last decimal? 

Otherwise we get smart levels that are corrupted becaused 1.10 becomes 1.1 and the re-import does not work. 
Try it here: http://opensalt.opened.com/cftree/doc/8 

<img width="298" alt="screen shot 2017-09-18 at 3 23 20 pm" src="https://user-images.githubusercontent.com/14943151/30567462-57762e30-9c85-11e7-9ca3-97bf844a32e5.png">
[case (25).xlsx](https://github.com/opensalt/opensalt/files/1312458/case.25.xlsx)

**Comment by brandonopened** [comment]
Start with: http://frameworks-staging.act.org/cftree/doc/117
Export as Spreadsheet. 
Currently the import looks like this: http://frameworks.act.org/cftree/doc/8 .

**Comment by roverwolf** [comment]
Fixed with #146
