### ISSUE TITLE
Cannot export imported frameworks due to wrong URI

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#142]
See: http://frameworks.act.org/cftree/doc/12

The URI is incorrect and prevents a download from happening via CASE. 

The framework was loaded from an external server.

**Comment by roverwolf** [comment]
I'm not sure this is entirely a bug, but part bug and part "let's get importing straight" issue.

- How was the framework "loaded from an external server"?
- Was the intention to make a derivative version or a copy of the original?

The displayed URIs are correct for references to an external server with a local copy, but they don't seem to be resolving correctly for some reason.
- Is the expectation that you would be redirected to the other server even though there is a local copy?
- Would it be better to remove the `http://frameworks.act.org/uri/` part on the displayed URI?

**Comment by roverwolf** [comment]
Fixed with merge of PR #145
