### ISSUE TITLE
User cannot delete a comment once it has been upvoted

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#143]
frameworks-staging.act.org . 

user commenter, pw commenter

Make a comment, Login as another user and upvote that comment

Now login as 'commenter' user and I cannot delete the comment now. Did not see an error message.

**Comment by roverwolf** [comment]
For consistency, should this be marked as [Severity 3](../wiki/Label-Definitions---Severity-Levels) insead of 2?

**Comment by brandonopened** [comment]
jorgeluis [11:11 AM] 
*What did you do yesterday?* fixed issue #143
*What will you do today?* Adding tests to get the branch merged

**Comment by roverwolf** [comment]
Jorge's fix has been merged.
