### ISSUE TITLE
Migrate frameworks to a command-handler model from CRUD

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#150]
Data Separation - database logging  (Multiple Users + Un-do). Implement actions for things like undo, cancel changes within a session, etc.  The code should move toward a command/handler pattern instead of doing CRUD directly so that the (reversable)

Desired features:
 - history
 - revert
 - undo
 - notificaiton of changes

**Comment by roverwolf** [comment]
An [FRD](https://docs.google.com/document/d/1xx849Tc-oeqYOTCW3sffcY57e0QUUXUwvou-cL1O9Mw/edit#heading=h.ts52palmhrqw) has been written for this feature.

**Comment by roverwolf** [comment]
Split desired features out as separate issues that can be implemented independently:
  - history (audit log) - #318 
  - notification of changes - #319
  - revert/undo - #320

**Comment by roverwolf** [comment]
Migration to a command-handler model is implemented by PR #294
