### ISSUE TITLE
Locking framework when being edited to avoid simultaneous edit issues

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#153]
framework lock for editing by a user so that two users cannot simultaneously edit it.  disallow editing functionality in backend and UI when a framework is locked (by someone else), add a  framework locks table framework, locker, timeout

**Comment by roverwolf** [comment]
This not needed once #150 is done, so not sure we want to implement it.

**Comment by roverwolf** [comment]
Closing in preference to #150
