### ISSUE TITLE
Logging in on CF_Items view page, or any page should stay there.

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#1556]
When you link to the URI for a CF_item, you get the item detail view but no tree (e.g. the JSON data view in HTML). If you log in from there, you should stay on the page and then be able to visit the tree view (if you have access).

In general, the issue is that you should stay on the page and view you are on when you log-in.

**Comment by roverwolf** [comment]
@jmarks The second part "you should be able to access the tree view unless the framework is private" should be a separate issue as it is a second change.  Currently the "Show in tree view" button is shown to anyone who can view the page (i.e. know the URI).  Restricting users from being able to go to the tree view does not make any of the data more private as if one knows the URI then they can fetch the framework via the API and get it all anyway.

**Comment by jmarks** [comment]
Bug description updated to the more general, stay on the page you are on when you log in.
