### ISSUE TITLE
Update the user guide on how to use the commenting feature

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#168]
The optional commenting feature should be documented in the user guide (for when it is enabled).

Related to #112

**Comment by brandonopened** [comment]
Section 7 updated in official User Guide, https://docs.google.com/document/d/1dlPZDV3w71ISGrfG8RwMc5Ug2tNGjjekWNeknqsEMww/edit#heading=h.i1y736cr6lfg
