### ISSUE TITLE
Support web browser based XSS.

### ISSUE THREAD

**Issue by Lomilar** [opensalt/opensalt#169]
Currently, CORS headers are not set on the OpenSALT application, preventing web browsers from using the CASE API except on websites that share the same domain.

Setting the following headers on the CASE API will allow client-side web applications to query OpenSALT across server boundaries (via XMLHTTPRequest, $.ajax, etc).

Access-Control-Allow-Headers: If-Modified-Since, Content-Type, Content-Range, Content-Disposition, Content-Description
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS
Access-Control-Allow-Origin: *

More details at:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by roverwolf** [comment]
The primary use case for the CASE API so far has been server to server access, but I agree that there are many use cases that make sense for browsers to access the CASE API endpoints as well.

As a new feature, cross-site requests should probably be added fairly soon.
