### ISSUE TITLE
change DocTree/Item view page to allow for Reviewer Role

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#178]
We need to add a user role that has NO edit access; only can view frameworks and export a framework (same as an unauthenticated user) BUT with access to the commenting function. This ticket is for enabling these users proper access when using OpenSALT

**Comment by roverwolf** [comment]
How does this differ from #177 ?

Does this also mean that users without the `Reviewer` role should *not* have access to commenting?
In what ways?
 - Should users without the role be able to view comments?
 - Should the `Reviewer` role be inherited by other existing roles?

**Comment by roverwolf** [comment]
Moved to 1.4 to be with other reviewer role issue.
