### ISSUE TITLE
User (ie not editor, admin, SE, SU) should not see 'create framework' and 'import framework' buttons

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#180]
Test using username noncommenter pw noncommenter on frameworks.staging.act.org .  Should not see buttons and only be able to comment on frameworks and export a framework - no other editing features.

**Comment by brandonopened** [comment]
<img width="424" alt="screen shot 2017-09-27 at 9 27 41 am" src="https://user-images.githubusercontent.com/14943151/30922992-5a207ab8-a370-11e7-80b6-7ab9812c4443.png">

when logged in these buttons should not appear for a "User"

**Comment by roverwolf** [comment]
Fixed.
