### ISSUE TITLE
Support expanded unicode character set

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#187]
Georgia has run into an error when trying to save some math statements.  It appears that at least one of the characters in the statements are currently unsupported in the database (𝑑).

The error showing up in the logs is

> E[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9D\\x91\\x91 =...' for column 'full_statement'

The database (and database configuration) should be modified to use utf8mb4 instead of utf8 to allow for unicode characters outside the Unicode Basic Multilingual Plane set.

Known character with issue: 𝑑 (\u1d451 -- d835 dc51 -- \xF0\x9D\x91\x91)

**Comment by brandonopened** [comment]
@JorgeLu1s please ensure this would be ok for our current instances.
