### ISSUE TITLE
Framework Edit function issue 

### ISSUE THREAD

**Issue by JMON10** [opensalt/opensalt#1870]
Selecting the edit function to modify an existing framework displays a loading screen that does not allow edits. There are no issues with other modifying functions such as adding child items, etc. 

Version- Version 3.2

Steps | 
Select a Framework
Click on any item within framework (parent, child, etc.)
Select tree view and select item details below 
Select edit function

Expected- Edit options should be displayed 

Actual- Selecting edit displays a loading screen only 

 - Device: Mac desktop 
 - OS: MacOS 11
 - Browser- Edge

**Comment by jmarks** [comment]
Effects dev branch on Sandbox
