### ISSUE TITLE
CASE API output: HTML in fullStatement

### ISSUE THREAD

**Issue by Lomilar** [opensalt/opensalt#192]
According to the CASE spec, markup is not supported. (per discussion 2017-10-05, haven't checked spec) 

For purposes of interoperability, markup should be stripped from descriptions and other data.

Example can be found here: https://case.georgiastandards.org/ims/case/v1p0/CFItems/fdb88d62-471f-11e7-8060-d3a48223711c

**Comment by roverwolf** [comment]
The javascript is rendering the statements as html instead of text.

Related to #170

**Comment by jmarks** [comment]
While this is well reasoned, we do not want to disallow content that is already available for other sources with some level of tagging in them. A filtered set of HTML tags is better then breaking existing content.  At the most this shoudl be a configuration option.

**Comment by roverwolf** [comment]
@jmarks The markdown addition will now escape all HTML tags.

If there are specific tags we need to consider as being valid to be displayed then please open an issue for that.
