### ISSUE TITLE
Add admin re-set two factor option in Manage Users

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#2043]
With the new Two factor, once a user set-up a validator client, there is not way to change it If they loose their phone they are locked out. Please add an admin function to manage users to re-move or re-set the two factor client configuration for a user. 

Similarly, there needs to be a way for an admin to re-access without two factor in case they are locked out.

**Comment by roverwolf** [comment]
Admins can now reset the two factor configuration for other users (commit eb91b3e537454c7dad9b142c5ce5a1f5570aa15b).

An admin will have to request another admin in their organisation or a super user to reset their configuration.
