### ISSUE TITLE
general questions about the uploading template (spreadsheet version)

### ISSUE THREAD

**Issue by minjeiYeo** [opensalt/opensalt#2065]
I didn't know where to contact for the question so I left it here.
Currently, I was focusing on testing spreadsheet uploading and that brought me couple questions
1. Is it possible to upload to set up CFSubjects from spreadsheet template uploading?
   (I checked CFItemTypes and CFLicenses are automatically set up from CFItem in the template)
2. How to set up CFRubrics?
3. Any support email for further questions?

Thanks in advance

**Comment by jmarks** [comment]
Rubric is not supported in the import sheet nore the UI. That is a roadmap item if you would like to contribute. see opensalt.org for support info (or email jmarks@pcgus.com), Also see docs.opensalt.org.
