### ISSUE TITLE
add sequenceNumber to import CSV process

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#212]
listEnumeration is not imported on csv import of a framework

**Comment by roverwolf** [comment]
We might want to make sure that `sequenceNumber` could also be imported from the CSV.

**Comment by brandonopened** [comment]
That’s where we need to discuss. Which is the intended value for ordering? Sequence number not list enum? And then human coding as a backup if those values don’t exist?

**Comment by brandonopened** [comment]
Jorge’s current PR is Just for proper numerical ordering but like your comments pointed out in general a broader strategy is needed

**Comment by roverwolf** [comment]
Note that [listEnumeration](https://www.imsglobal.org/sites/default/files/CASE/casev1p0/information_model/caseservicev1p0_infomodelv1p0.html#DataAttribute_CFPckgItem_listEnumeration) may not be useful for ordering as `listEnumeration` is the characters that are used for denoting the item in the list (from the official document such as a PDF), not necessarily a numeric value.

Examples include:
 - 1, 2, 3
 - 1), 2), 3)
 - a., b., c.
 - \*
 - ⮞
 - →

**Comment by brandonopened** [comment]
Not list enumeration, sequence number - https://drive.google.com/open?id=1idJv2lHCU4xojCSm5vh_zBFhgUGQvvaNSwmdSzD3QIc
