### ISSUE TITLE
Hide comments for public?

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#217]
Suggestion from the math team is to hide the comments to only "reviewers". 

It looks like the code can be modified here on view.html.twig

  {% if 'comments' is active feature %}
          {% if viewerRights %}
            {% if not is_granted('comment') %}
                <p>To comment please login first</p>
            {% endif %}
            <div class="js-comments-container" data-lsdocid="{{ lsDocId }}"></div>
        {% endif %}
        {% endif %}

I don't think 'viewerrights' is the right label... but for the 'reviewer' role do we call it viewer or role 0? (that is, no role essentially) https://github.com/opensalt/opensalt/blob/e0636523d3ca4be84661852be80ba17e36fb1099/src/Salt/UserBundle/Command/UserAddRoleCommand.php  ?

**Comment by brandonopened** [comment]
I tried 'if userRights' and 'if UserRights' with no success for logged in users to see comments, but the public to NOT see comments... so close! (awaiting word whether or not we want to do this anyway).

**Comment by brandonopened** [comment]
Missing tests, but the code in this branch works locally: https://github.com/opensalt/opensalt/tree/public_no_comments . (shows no comments for public user, but allows commenting for a User. The change is in view.html.twig)

**Comment by roverwolf** [comment]
This issue is probably related to #177 if we still want to be adding a specific role for reviewers.
