### ISSUE TITLE
Error with multi delete

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#220]
Enable check marks in tree, and select several or a whole branch of items, then select delete from the action menu. You get an error (Two) display dialog. Often the delete does work however.

**Comment by roverwolf** [comment]
For reference, this is on OpenSALT version 1.1

**Comment by brandonopened** [comment]
@jmarks did you mean to put this in release 1.4? It seems fixed now

**Comment by roverwolf** [comment]
@jmarks Please verify you are satisfied that this is fixed and close the issue.
