### ISSUE TITLE
Can not add new Item Type

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#221]
Create or edit an item, and enter a new item type not on the list. You get an error and can not crate a new item type.

**Comment by roverwolf** [comment]
For reference, this is on OpenSALT version 1.1

**Comment by brandonopened** [comment]
Isn't 1.2 production? can we upgrade (i assume georgia)?

**Comment by brandonopened** [comment]
I see this error in the console: site-d5e287cbb1.js:9200 POST http://frameworks-staging.act.org/cfitem/new/89/73573 422 (Unprocessable Entity)

**Comment by jmarks** [comment]
Well, it seems I can add in some cases. When you click on the input field for item type, the item type drop list is displaces to the top of the dialog:

![image](https://user-images.githubusercontent.com/1319413/32127773-07badb08-bb2e-11e7-8e6d-fca875d6b486.png)
