### ISSUE TITLE
Add underline capability to markdown

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#229]
Re: https://github.com/opensalt/opensalt/issues/106 

This markdown flavor does not support underlines. Underlines are needed for customer data frequently. Please add mark for underline.

**Comment by roverwolf** [comment]
By default, markdown syntax does not support underline (even [GitHub's](https://guides.github.com/features/mastering-markdown/) doesn't).  Note that HTML4 deprecated the tag that used to be for underlining text and HTML5 dropped it.

What token should be used to denote that the text should be underlined?
-  "_"? (like "\_underlined text\_" which would normally be displayed in italics?)
- Adding some way to add a CSS class to a set of text?

**Comment by roverwolf** [comment]
@jmarks Any suggestions/requirements on what you want for syntax?  Or should this be closed?

**Comment by jmarks** [comment]
I think we should look to support HTML underline but not in this release time-frame and also deal with the IMS Global CASE best practice issues.

**Comment by roverwolf** [comment]
Noting that HTML 5 does not directly support underline.  That is now done
with CSS.

**Comment by roverwolf** [comment]
#256 adds the ability to use the (wrongly interpreted) \<u> tag.

From https://www.w3.org/TR/html5/text-level-semantics.html#the-u-element

> The u element represents a span of text with an unarticulated, though explicitly rendered, non-textual annotation, such as labeling the text as being a proper name in Chinese text (a Chinese proper name mark), or labeling the text as being misspelt.

> In most cases, another element is likely to be more appropriate: for marking stress emphasis, the em element should be used; for marking key words or phrases either the b element or the mark element should be used, depending on the context; for marking book titles, the cite element should be used; for labeling text with explicit textual annotations, the ruby element should be used; for technical terms, taxonomic designation, transliteration, a thought, or for labeling ship names in Western texts, the i element should be used.

> **Note:** The default rendering of the u element in visual presentations clashes with the conventional rendering of hyperlinks (underlining). Authors are encouraged to avoid using the u element where it could be confused for a hyperlink.

@jmarks With this, did you want to mark this as part of 1.3 and close it?

**Comment by jmarks** [comment]
@roverwolf If I understand why you are saying, the limited HTML tags being added in 1.3 cover the intent of the underline user. If so, Yes we can close this.
