### ISSUE TITLE
Wrap text on Tree view

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#239]
<img width="1440" alt="opensalt-ui-after" src="https://user-images.githubusercontent.com/14943151/32513489-3668c224-c3af-11e7-94aa-c8a4cec15b16.png">
<img width="1438" alt="opensalt-ui-before" src="https://user-images.githubusercontent.com/14943151/32513490-36a0f040-c3af-11e7-85a9-c42c3e6099b1.png">

" This is essentially what I tweaked:
 
item
    background-color: #F2F4F7;
    padding: 5px 5px 5px 10px;
    margin: 0px 0 0 5px;
    font-size: 16px;
    line-height: 21px;
 
.item-humanCodingScheme {
    font-weight: 400;
    color: #777;
    font-size: 14px;
    letter-spacing: .075em;
    margin-right: 5px;
}
 
item icon
    opacity: .5;
    margin-top: 8px;
 
Expander
    margin-top: 10px;" 

(from Mark Kopulus, ACT UX)

**Comment by chrischaloux** [comment]
reviewed on 11/9. Brandon to update ticket with proposed solution. Will be discussed again during OpenSALT meeting on 11/16.

**Comment by brandonopened** [comment]
we will not do this right now
