### ISSUE TITLE
Toggle full screen of either tab (tree or CF item)

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#244]
There should be a toggle for full screen of tree view. 

As any logged-in user on the CFtree view, I should be able to click a button on either panel to make that panel full screen. Would address #242 and #239 simultaneously @jmarks thoughts?

**Comment by brandonopened** [comment]
thoughts on this flow? 
[Presentation1.pptx](https://github.com/opensalt/opensalt/files/1459483/Presentation1.pptx)

**Comment by jmarks** [comment]
I like the proposal, conceptually, but the wireframes are not clear. The ability to drag the divider to the left or right might be a better approach for the tree issue you have. It woudl also loow for giving more width to the item and association views. It is really editing an item body that going full screen would be most helpful (issue #242). 

The tree's challenge is not width but height.

**Comment by brandonopened** [comment]
Better: 
<img width="1183" alt="screen shot 2017-11-17 at 9 17 56 am" src="https://user-images.githubusercontent.com/14943151/32965264-e159e1d0-cb8a-11e7-8aaf-5553b482a4c0.png">
