### ISSUE TITLE
Confusion regarding deployment on remote server

### ISSUE THREAD

**Issue by msandbothe** [opensalt/opensalt#249]
I have gone through the installation process and gotten all successes as far as I can tell. I am inexperienced with Docker and unsure which configuration files I need to change so that the open-salt web application can be accessed from a remote machine. Any help would be appreciated.

**Comment by roverwolf** [comment]
The `docker/docker-compose.yml` file exposes a port for the nginx container (default 3000), so using http://<server>:3000/ should work if that port is allowed through your systems firewall.

You can add `PORT=80` to the `docker/.env` file or directly change the value around line 40 in `docker/docker-compose.yml` (and then restart using `docker-compose down -v; docker-compose up -d`) to change what port is used.

Note that it is generally expected that the OpenSALT container would be behind a proxy that handles SSL termination, so no support is currently in place for SSL.

**Comment by msandbothe** [comment]
Thank you. The issue was with our firewall setup. Pointing me to where I could edit the port in the .yml was helpful too.

**Comment by roverwolf** [comment]
Glad it helped.  Feel free to reach out if you have any other questions, suggestions, or anything else.
