### ISSUE TITLE
Uncaught RuntimeException: Unable to create the cache directory

### ISSUE THREAD

**Issue by msandbothe** [opensalt/opensalt#250]
I get the following error in my browser once I have logged in

`Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/var/cache/prod) in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:674 Stack trace: #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(574): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/html/web/app.php(26): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 674`

The only issue that references this I see is #88 but am unsure what the reporter means by "php mirror has no permission" and how they rectified that.

**Comment by roverwolf** [comment]
This indicates a permission issue on the cache directory.

Try `chmod -R 777 var/cache` from the top directory of the checked out repository (you might need to use sudo if you get an error).

**Comment by msandbothe** [comment]
That worked. Also had to chmod the var/logs directory. Thanks

**Comment by roverwolf** [comment]
Now documented at [Troubleshooting](https://github.com/opensalt/opensalt/wiki/Troubleshooting)
