### ISSUE TITLE
Document possible issues importing from ASN

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#252]
Now that we are expecting items to have markdown syntax and never HTML we should document that in the user guide.

Specifically that a manual pass will be required for things like importing from ASN where anything with HTML will need to be fixed and there could also be accidental markdown syntax that gets interpreted.

**Comment by brandonopened** [comment]
Could be solved with #253

**Comment by roverwolf** [comment]
This should be less of an issue now that we decided to allow some HTML (specifically ul, ol, li, b, i, u, br, p tags) (implemented with #256).

The documentation should still be updated mentioning that most HTML tags will be removed.
