### ISSUE TITLE
please put https://github.com/opensalt/opensalt/tree/feature/kms-2279 on salt-dev

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#258]
Hi Dave, Can you have salt-dev or another instance run that branch so Josh can provide feedback? Thanks.

**Comment by roverwolf** [comment]
Done.

@jmarks salt-dev now has the branch with the movable bar.

@brandonopened The first thing I noticed was that the bar does not move as you drag it, making it hard to tell what is going on.
