### ISSUE TITLE
increase abbreviated character limit

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#266]
Remove the abbreviated character limit in the DB. Download the attached file and just give it the extension csv since github won't let me upload those types ;-) 
[sample_case_abbrev.txt](https://github.com/opensalt/opensalt/files/1507008/sample_case_abbrev.txt)

**Comment by roverwolf** [comment]
I assume "Remove" actually means "Increase" as the column cannot be of infinite size.  What should the new limit be?

Are there other fields that should have their limit increased besides the abbreviated statement field?

**Comment by brandonopened** [comment]
Can you point me to where we specify the current DB field file types/limits? I couldn't find it searching the github repo. Then I or a dev could do a comparison between that and the specification line by line to make sure we are consistent. (And yes, remove meant increase)

**Comment by roverwolf** [comment]
We specify the DB fields in the source code as annotations on the entities.

The latest information about the spec I could find that showed characters limits is https://docs.google.com/spreadsheets/d/1NVMGsjcQQKNYNGQkkQ58CTSxbskCVBre-KTttnACuMc/edit#gid=442470250

**Comment by roverwolf** [comment]
Character limit has been increased to 60 characters by #275
