### ISSUE TITLE
add alphabetic list support in markdown

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#271]
Currently the markdown syntax used does not have support for alphabetic lists and thus HTML needs to be used instead.

Consider adding a markdown syntax extension to add support for alphabetic (and roman numeral?) lists.

**Comment by brandonopened** [comment]
https://stackoverflow.com/questions/13366820/how-do-you-make-lettered-lists-using-markdown

**Comment by roverwolf** [comment]
Note that the referenced link in the previous comment shows:
  a) how to make **all** lists alphabetic,
  b) how to use HTML to make the lists, and
  c) the Pandoc syntax for `fancy_list` -- this might be similar to the syntax we would like to use for a markdown syntax extention
