### ISSUE TITLE
License and License URI are missing from CF Doc

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#283]
The document and package need a license and license URI value in the create and edit form. It is part of the data model but you can not access it. 

Sub-items:
 - [x] #332 View
 - [x] #333 Edit

**Comment by brandonopened** [comment]
I may not know enough about this but those fields aren't in the CFDoc table? 
<img width="109" alt="screen shot 2018-01-03 at 1 54 17 pm" src="https://user-images.githubusercontent.com/14943151/34584686-9a6b2be8-f151-11e7-9392-4de6658862c6.png">

licenseURI and License_text are in a different table. I was able to get them to show up playing around with it on the CFdoc show page, but upon framework creation.

**Comment by roverwolf** [comment]
Correct, [CFLicense](https://www.imsglobal.org/sites/default/files/CASE/casev1p0/information_model/caseservicev1p0_infomodelv1p0.html#Data_CFLicense) is a separate object that can be referred to by a CFDocument and CFItem.

The biggest question is how should they be managed.  They are not "owned" by a single CFDocument in the CASE data model, but cannot be changed if any of the CFDocuments (or CFItems) that refer to it are in the "Adopted" status.

This is an issue that we have not solved which is common to other objects as well (CFSubject, CFConcept, CFItemType, CFAssociationGroup).

**Comment by roverwolf** [comment]
I believe this has been resolved by the linked issues.
