### ISSUE TITLE
loading linked documents on same server fails for large framework

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#295]
When loading a framework that is large and has associations to and from other large frameworks, the association view fails to load and display the related items in linked frameworks.

For example, view this item in the assessment "Content Specification" framework here: https://case.smarterbalanced.org/cftree/item/118134 

Not the "Exact Match Of" assococitions THere is one "local:[uuid] 0loading doucment" that never loads, or takes a very long time and maybe times out.

![image](https://user-images.githubusercontent.com/1319413/33958992-fa646d6a-dffa-11e7-8221-e11377456a12.png)

If you click to the next item down, then that link to that local framework is now down as "(document could not be loaded...)" and no links to the other framework are displayed.

![image](https://user-images.githubusercontent.com/1319413/33959105-505efdde-dffb-11e7-9f6b-1fb91d5dbbde.png)

**Comment by jmarks** [comment]
Is it possible to use the CASE API to get just the items needed as a lazy load and avoid loading the entire document?

As a work around, it seems you can force loading the document, if you know which one it should be, by selecting it in the create associations tab. But this only works if you are logged in with edit rights and the framework.

**Comment by jmarks** [comment]
This may be the same as https://github.com/opensalt/opensalt/issues/315

**Comment by vinisheth07** [comment]
Hi All
Github Issue - 295 The issue of loading linked documents - we have found that it takes about 5-6 minutes for linking the document to load. Please find the attached video same.
[Github_295_Video.zip](https://github.com/opensalt/opensalt/files/1663537/Github_295_Video.zip)
