### ISSUE TITLE
Adjustable tree/detail width breaks page when used

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#296]
Steps to reproduce:

Case 1:
- move the centre bar to resize the width of the tree and detail sections (wider or narrower)
- resize the browser to be narrower than the centre bar
- **ISSUE**
  - the height of the page is increased significantly
  - the detail section is missing
  - the "toggle" arrows go missing

Case 2:
- Using the *Safari* browser on a Mac
- Drag the centre bar left
- **ISSUE**
  - the "toggle" arrows do not move with the bar

Caused by #263

**Comment by roverwolf** [comment]
#288 is related to this issue

**Comment by roverwolf** [comment]
![selection_20171213t142247](https://user-images.githubusercontent.com/210211/33965649-8e985fda-e011-11e7-96a1-e326f98c7e48.png)

**Comment by roverwolf** [comment]
![safari-toggle-arrows](https://user-images.githubusercontent.com/210211/33965799-18edd03e-e012-11e7-8388-5e65798d8c9b.png)

**Comment by anuradhas248** [comment]
@roverwolf - I have fixed all mentioned issues on feature/kms-2279 branch. QA team also verified issues. Please verify from your side. Also complete code review of newly added code.

**Comment by roverwolf** [comment]
@anuradhas248 Please create a new pull request from the branch so that it can be reviewed and merged.

**Comment by Vishvesh-LM** [comment]
What I learnt from the offshore team this morning:
1. The first of the two issues -  height of page, missing detail section - seemed to be pre-existing. They tested it on prod and found it there too. The action item for team there is to add test cases to specifically test the responsiveness of the UI.
2. the second issue - toggle buttons not moving on Safari on Mac- should've been caught during testing.  Again, test cases being added.

We've run the acceptance test suite today. And the team will be running it - without fail - whenever anyone is 'development complete' with any feature/bug fix.

**Comment by roverwolf** [comment]
I'll note that the detail section is **NOT** missing in the released v1.3 version of OpenSALT in a small window (it shows up on a small window on the desktop as well as a cell phone).

![selection_20171214t090819](https://user-images.githubusercontent.com/210211/34005183-ed9c9896-e0ae-11e7-9ba0-aec741b2171d.png)

**Comment by vinisheth07** [comment]
Hi All,

Above all issues are fixed on the staging server. Find the document for the same.

[Github_Issues.docx](https://github.com/opensalt/opensalt/files/1660325/Github_Issues.docx)
