### ISSUE TITLE
Wrong margin

### ISSUE THREAD

**Issue by JorgeLu1s** [opensalt/opensalt#303]
There is an issue with the margin, the page is not centred, seems like this is the problem:

https://github.com/opensalt/opensalt/pull/299/files#diff-39dd1ad924b16df608eb4bb978b8384fR635

**Comment by roverwolf** [comment]
Yes, the added margin:10px on line 635 of view.scss is causing the page to not be centred.

The changes to lines 3-7 in view.scss are also issues as they are making the document title row narrower than it shoudl be as well.
