### ISSUE TITLE
Documents exported as spreadsheets has single quotes at the beginning and end of filename.

### ISSUE THREAD

**Issue by lmsilvera** [opensalt/opensalt#313]
These are the cases:

Firefox 57.0.4: single quotes appear
Chrome 63.0.3239.132: single quotes don't appear
Safari 11.0: single quotes appear

![image](https://lh3.googleusercontent.com/6SSNTq4FODVkTrldrEBIgfc0XfdWmQ39rJTQzdEKbRSLS7cLUMKusi1wWN602lZvWP2Ikdaq1G_25NsqRoZZ=w1440-h785)

**Comment by vinisheth07** [comment]
Hi All,

Github issue - 313 - Exported spreadsheets having quotes in the file name - Still exists on Safari and Firefox whereas working proper on Chrome browser.
