### ISSUE TITLE
Pending status for new users - KMS-3107

### ISSUE THREAD

**Issue by BarbAllen** [opensalt/opensalt#316]
This story is for the database changes that need to happen in order to accommodate the new status of Pending.
1. Rule: New user account will be defaulted to Pending
2. Rule: New user account - User type will be defaulted to Viewer
3. Rule: One status only per user account 

Note: The NEW user account is to be given a status of Pending.  Based on SPIKE, the pending status may be a derivative of suspended status.

The User type defaulted to Viewer

The UI will accommodate the setting of these two fields (role type and status) - later story.

Three statuses need to be available - Active, Pending and Suspended

**Comment by roverwolf** [comment]
Implemented by #323
