### ISSUE TITLE
The creator of a framework cannot see imported files

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#321]
I created a new framework and uploaded a CSV file. http://frameworks-staging.act.org/cftree/doc/416# 

I see a blank document but there are clearly statements present - others can see the statements as well. 

- Cannot see statements when signed in
- Cannot see statements when not signed in
- CAN see statements with incognito tab
- Also CAN see statements when doing a hard refresh in Chrome (shift command R)

Please check the code to see if it is not clearing the cache perhaps? 

*Only happening on ACT instances (Heroku-related bug probably)

**Comment by BarbAllen** [comment]
KMS-3332
