### ISSUE TITLE
in dev branch cannot create association groups

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#329]
Tried on stable 2.0 instance and local dev branch. Receive error 500 when trying to create a new association group

1) As an editor/org admin I login to a framework
2) Navigate to a framework and select "manage association groups"
3) Error 500 reported in console, UI hangs

**Comment by roverwolf** [comment]
@brandonopened This appears to be working for me.  Does it still give you an error?

**Comment by brandonopened** [comment]
It does now.. 2.1 stable. I'll take it.
