### ISSUE TITLE
404 errors should have a nicer message

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#349]
When going to a page that is "Not Found" we are getting an error-like message instead of a more friendly message saying that the page is not available.

![selection_20180202t115007](https://user-images.githubusercontent.com/210211/35752013-40f880f4-080f-11e8-9658-e323d4c0808f.png)

**Comment by brandonopened** [comment]
Can we have a cartoon salt shaker that the lid fell off or something? 
http://douglascountyfederation.com/wp-content/uploads/2014/08/Salt-Shaker-1024x804.jpg

**Comment by roverwolf** [comment]
@brandonopened Sure, we just need to find something with an appropriate licence.

**Comment by jmarks** [comment]
I like th eidea, but the message is also important. and we need all the common errors. The messages need to be clear such as "This page does not exist, it might have been deleted. please select another framework. or item" (Links to other stuff).

We should also add a report issue link to github or a configurable URL or message for help.

**Comment by brandonopened** [comment]
Ok, early this coming week I’ll put some basic templates up for this purpose as well as general purpose and a video for bug reporting. 

I like the approach: help with troubleshooting, offer a path to continue working, steps to file a bug or feature that is generic and realizing our end users aren’t devs

**Comment by roverwolf** [comment]
I would suggest that the more advanced messaging (how to enter issues, etc.) are more applicable to errors other than the 404 - Not Found page.

In general, that page is most often going to be shown when going to a page that never existed or may have been deleted.

I do agree that the more general error page could use some of the extra information.
