### ISSUE TITLE
Approve button does not resume back (KMS-3489)

### ISSUE THREAD

**Issue by adlearningmate** [opensalt/opensalt#373]
Login as superuser
Click on add a new user button from user manage page
fill all require fields
Click on add button
new user is listed on user list page (with show, edit, suspend and approve buttons)
 click on suspend button
suspend button changes to unsuspend button (edit and approve button are hidden)
click on unsuspend button (show, edit, suspend button are displayed but still approve button is hidden)
Note: if super user by mistake or want to approved suspended user to approve again should have that functionality

Actual:

Approve button does not resume back

Expected:

Approve button should get resume back along with edit button if click on unsuspend button

For more clarification please refer to attached video

**Comment by roverwolf** [comment]
There is only one status field, and my understanding from @JorgeLu1s was that the state diagram is supposed to look like the following:

![5422468671995904](https://user-images.githubusercontent.com/210211/36107998-86953d64-0fd0-11e8-8981-9bebfe643fb7.png)

If this is not correct then we should document the correct state diagram.

**Comment by brandonopened** [comment]
The diagram is correct - once pending has become 'active' it never needs to go back to pending, it can only become suspended at that point.

**Comment by roverwolf** [comment]
@brandonopened Please confirm that this issue (and PR #374) is not needed and can be closed.

If an admin suspends a user from the pending state then there is no need for the "Approve" button to be displayed again at a later time as "Unsuspend" will make the user active the same as "Approve" would have from the pending state.

**Comment by JorgeLu1s** [comment]
This issue will be closed since this is not a required feature
