### ISSUE TITLE
Can someone point me to the code for the spreadsheet importer

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#377]
Before I write a bunch of stories I'd like to be able to see exactly what it's doing now. Can't find the code currently.

**Comment by roverwolf** [comment]
The javascript is in [app/Resources/assets/js/lsdoc/index.js](https://github.com/opensalt/opensalt/blob/develop/app/Resources/assets/js/lsdoc/index.js) which then submits the file file which goes through  `ExcelImportController`, `ImportExcelFileComand`, and `ImportExcelFiileHandler` which calls the `importExcel` method in [src/App/Service/ExcelImport.php](https://github.com/opensalt/opensalt/blob/develop/src/App/Service/ExcelImport.php)

**Comment by brandonopened** [comment]
Thanks!
