### ISSUE TITLE
Add all CASE fields to spreadsheet import  - KMS-3718

### ISSUE THREAD

**Issue by BarbAllen** [opensalt/opensalt#409]
Making sure all of the CASE fields are in the spreadsheet importer.
pertains to Editor function - Import spreadsheet framework

EXPLAIN ISSUE OR BUG WITH GHERKIN TEXT

EXAMPLE USER STORY:

AS A user with access to create items  
I WANT the legacy processes and workspace processes to create items in an identical manner  
SO THAT duplicate items and gaps in items do not get generated

**Comment by brandonopened** [comment]
https://docs.google.com/spreadsheets/d/1Iz8QisnuVCoQ9YUhpZcrJVQo-m3-trR4tZ1MAUxLfPk/edit#gid=1281760212 .

**Comment by roverwolf** [comment]
Does it make sense to put all the CASE fields in the spreadsheet?
Is the intent to be able to import it into a different OpenSALT instance (as a derivative) and link back to the original?
The original intent was to be able to export a spreadsheet and then import it back after making changes, and allowing some fields to be changed (URIs) could cause issues doing that.

We may need to look at having multiple spreadsheets for the different purposes.

**Comment by brandonopened** [comment]
https://docs.google.com/spreadsheets/d/1PE8zS_MgFsmwARNHlbdZltZhAQEI72ZraTlV10grjLg/edit#gid=106010621

Sample Data that should work: https://docs.google.com/spreadsheets/d/1oxfpAVVkJIaNRZqdfBRevTusOvcbb2xzqjlOQpCILiM/edit?usp=sharing

**Comment by brandonopened** [comment]
Ok, modified set of CASE fields... what is on the importer should be on the exporter as well to make sure it works
