### ISSUE TITLE
Update Import Spreadsheet UI - KMS-3766

### ISSUE THREAD

**Issue by BarbAllen** [opensalt/opensalt#412]
AS an OpenSALT Editor I want to import a framework using the UI so that the UI will give me options Update or Create a Derivative choices.

Actions:
1.The OS Editor will be able to click to see the Spreadsheet guide
2.The OS Editor will be able to browse to select a spreadsheet file
3.The OS Editor will be able to choose Update or
4.The OS Editor will be able to choose Create a Derivative

 

EXPLAIN ISSUE OR BUG WITH GHERKIN TEXT

EXAMPLE USER STORY:

AS A user with access to create items  
I WANT the legacy processes and workspace processes to create items in an identical manner  
SO THAT duplicate items and gaps in items do not get generated

**Comment by brandonopened** [comment]
Multiple PR's closed this
