### ISSUE TITLE
Left right exand broke aspects of layout behavior (Scaling and centering). 

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#437]
In OpenSALT 1.3, on very large screen, the application is centered in the browser:

![image](https://user-images.githubusercontent.com/1319413/37684631-e7323110-2c4d-11e8-9970-198c9f0b6972.png)

However, in 2.0, it is left justified

![image](https://user-images.githubusercontent.com/1319413/37684678-09b0952e-2c4e-11e8-822a-0e26c6e8250d.png)

Also note the misaligned scroll bar on the right (item detail), which is one scroll bar width to far right in the 2.0 layout. 

Also note the very poorly configured and nested layout on a narrow screen width:

![image](https://user-images.githubusercontent.com/1319413/37684901-c7ac1bac-2c4e-11e8-843d-05253493ce0a.png)

The logic/rules for the responsive display needs to be refined:
1) the left/right toggle panel should be a dragable div segment line so you can place it anywhere, with the default centered (detinted so it snaps there easily or re-sets on refresh of browser).  
2) The divider goes away at the responsive trigger point to stack the left/right panels (And it should be more clear that that there are stacked panels.)
3) The layout should either have no max width, or be centered when it hits the max width. If we stick with a max width, it should be wider then the current.
4) under no circumstances shoudl the layout present nested scroll bard as illustrated above... ever.

**Comment by roverwolf** [comment]
This has already been fixed in 2.1.
