### ISSUE TITLE
deprecate github and ASN from importer

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#458]
Github integration was useful but is not being used by many users, we should deprecate it for 2.1

**Comment by roverwolf** [comment]
Question:  Should it just be marked in the release notes for deprecation (which release will it be removed in) or is a message to be added when used... ?

**Comment by brandonopened** [comment]
Remove tabs for ASN and github on Importer.

**Comment by jmarks** [comment]
Removing the ASN tab is needed for 2.1.1 patch, as a priority. Upload JSON file should accept either CASE or ASN formatter JSON files. Also remove all references to ASN in the ui and code.

**Comment by brandonopened** [comment]
closed by #571
