### ISSUE TITLE
URI links not working always?

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#471]
on http://frameworks.act.org/cftree/item/19974
http://frameworks.act.org/uri/d833a66c-2176-4240-b4fa-320dee00e87b
the CASE item URI link doesn't work.

I cannot replicate this bug with other frameworks; is it because we loaded this framework over a year ago? 

(URI links on opensalt.net etc seem to work)

**Comment by jonscheiding** [comment]
@brandonopened I believe that PR #578 will resolve this, let me know if you agree.

**Comment by brandonopened** [comment]
I do. Simple and elegant solution you had too, thank you!
