### ISSUE TITLE
Ability to configure the S3 service

### ISSUE THREAD

**Issue by lmsilvera** [opensalt/opensalt#476]
Provide a screen within OpenSALT to do the following:

Providing ability to turn the S3 storage ON/OFF
Providing ability to change S3 bucket path/URL
Providing ability to supply S3 creds to make connection between OpenSALT Server and S3.

**Comment by roverwolf** [comment]
These should possibly be environment parameters passed into the application instead of being in a screen and stored in the database as they are things that the system administrator would be setting.

**Comment by lmsilvera** [comment]
*Providing ability to turn the S3 storage ON/OFF*
Already exists a tool in OpenSalt (toggle-bundle) to turn ON/OFF features
*Providing ability to change S3 bucket path/URL*
We can store the S3 bucket in a environment parameters
*Providing ability to supply S3 creds to make connection between OpenSALT Server and S3.*
We can do that but only a connection per instance, I mean one OpensSalt instance could only has a S3 bucket creds (through environment parameters)

**Comment by roverwolf** [comment]
Completed by #549
