### ISSUE TITLE
Parent statements are not getting deleted while updating import framework

### ISSUE THREAD

**Issue by sajeed42** [opensalt/opensalt#483]
Thank you for your interest in OpenSALT!

Do the checklist before filing an issue:

- [ ] Label your issue as part of a larger epic such as "import/export", feature, bug, and *review* if you want us to see it more quickly
- [ ] Steps taken and version of OpenSALT you are working on (from the main opensalt home page, select 'about')
- [ ] List Operating System and Browser
- [ ] If you are able to report the URL where an error happened or output from the dev console please do so as well

EXPLAIN ISSUE OR BUG WITH GHERKIN TEXT

EXAMPLE USER STORY:

AS A user with access to create items  
I WANT the legacy processes and workspace processes to create items in an identical manner  
SO THAT duplicate items and gaps in items do not get generated
refer attached video file and spreadsheet

http://frameworks-staging.act.org/cftree/doc/676

**Comment by roverwolf** [comment]
Closing as PR #496 has been merged which indicates that it resolves this and the content of this issue doesn't actually say anything in the body, only the title.
