### ISSUE TITLE
addition of fields for OpenSALT for ACT internal use

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#504]
Overview video: https://www.youtube.com/watch?v=VRtCunZe8c8  

**As an ACT internal user, I want to be able to edit fields not currently in CASE.** 

Lance (ACT)
- Can’t we do this in standard, reusable way that also anticipates CASE compliance?
- Notion of user-defined metadata fields assigned to an entity…for now in OpenSALT, this could be defined via DB insert skipping a UI for creation
- NOT hard coded field names
- Implement the minimum number of required field types
- String?, List?, Integer?
- Implement the minimum number of constraints by field type…Length, Precision
- Expose the fields (tab) as “Custom Fields” not “ACT Fields”
- (Eventually) extend CASE to support custom metadata

David: 

- There is a json column (named “extra”) in the database table that is useful for this purpose.
- Are the custom fields system wide or might they be framework specific?
- How should the fields be defined?
  - Internal name of the field -- should the name be namespaced for future sharing compatibility?
  - Is a display label needed for the field?  Or is the internal name enough?
  - Type of the field -- Just scalars?  Allow lists?  Enumerated or free-form?  Validation?
  - Should we use a standard/draft standard like JSON Schema to define the fields?

**Comment by brandonopened** [comment]
Fields will be: 
- system wide (?) 
**Display**: propose system name and display name be the same whenever possible
**Use Cases**: We will be only needing to export among ACT internal servers, and eventually will build out to show in UI too. 
**Data types**: 
String (and length)
List (and Values)
Hierarchy (and Values and Parent/Child relationships)
Numeric (and Scale and Precision)
(others?)  - @JosephLeon can we start to list more about the fields based on what we know? Task model fields too.

**Comment by JosephLeon** [comment]
> Are the custom fields system wide or might they be framework specific?

They should be visible only on frameworks that had them imported via the extra column as a JSON object.

> How should the fields be defined?

So far the fields will be:

```
**Display Name -> internal_name**
Item Taxonomy Codes -> item_taxonomy_codes
Statement Origin -> statement_origin
Citations Text -> citations_text
Reporting Categories -> reporting_categories
```

> Is a display label needed for the field? Or is the internal name enough?

We could initially just use internal names and have a more thorough UI/db model later.

> Type of the field -- Just scalars? Allow lists? Enumerated or free-form? Validation?

They are all strings so far, some comma separated lists.

> Should we use a standard/draft standard like JSON Schema to define the fields?

We could start with something simple and move to JSON Schema later
