### ISSUE TITLE
Need a better icon for the math equation rendering button in the WYSIWYG

### ISSUE THREAD

**Issue by JosephLeon** [opensalt/opensalt#516]
Need a better icon for the math equation rendering button in the WYSIWYG.

Example:

```
.si-sigma:before {
  content: "\03a3";
}
```
AS A user with access to CRUD items 
I WANT the math equation button in the WYSIWYG to be a sigma symbol instead of wrench

**Comment by brandonopened** [comment]
Thank you :-)
