### ISSUE TITLE
Import issue with "adoptionStatus" field

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#528]
Importing a CASE file that was exported from the TEKS Texas Gateway site failed as they use *adopted* as the value of the `adoptionStatus` field.

OpenSALT has a list of values that are allowed (based on the best practices guide), including *Adopted* with a captial A, which allow workflow rules to be attached to the status.

How should we treat values of `adoptionStatus` that are not in our list?

**Comment by jmarks** [comment]
Adoption status value shoudl be case insensitive so "Adopted" and "adopted" are considered the same. Any unknown adoption status shoudl be mapped to draft.
