### ISSUE TITLE
Import issue with long "abbreviatedStatement" values

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#529]
Importing a CASE file that was exported from the TEKS Texas Gateway site failed as they have `abbreviatedStatement` values that are longer than expected (some over 1000 chars - they seem to be exactly the same as the `fullStatement` in this case).

We only allow 60 characters for an `abbreviatedStatement`.

The final CASE specification does not actually have any length limits stated for the field (or any other field).

**Comment by brandonopened** [comment]
Added to CASE github issues for CASE 1.1 revision of specification. 
https://github.com/IMSGlobal/CASE/issues/104 

Propose no backend limit on import of abbreviatedStatement but cannot create one within OpenSALT UI greater than 60?
