### ISSUE TITLE
The math button (sigma) should insert something a bit more helpful

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#533]
In https://github.com/opensalt/opensalt/issues/513 a new button was added for math.

The math button (sigma) should insert something a bit more helpful like "$Add_Latex_Here_(e.g 2x4)$"  There should also be a link to KaTeX reference available directly from the editor.

**Comment by roverwolf** [comment]
@jmarks These should be two separate issues.

**Comment by brandonopened** [comment]
How about this inserted when you press the math button:
$$ See https://khan.github.io/KaTeX/function-support.html for more information. Put your equations here!$$

or just " $$ OpenSALT uses KaTeX.$$ and on the toolbar make the link to the how-to clickable

**Comment by brandonopened** [comment]
hover-over mentions Katex. Yes eventually we want a click-button equation editor but couldn't find one compatible with our current tools.
