### ISSUE TITLE
Add custom ACT fields to OpenSALT (Backend)

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#543]
From 78 to 56 thus far.

[https://docs.google.com/spreadsheets/d/1W7301e5vn8F4dEAqxCVvTYqGqOZ1it1vWDOjG1go2bQ/edit#gid=1115616399](https://docs.google.com/spreadsheets/d/1W7301e5vn8F4dEAqxCVvTYqGqOZ1it1vWDOjG1go2bQ/edit#gid=1115616399)

[https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit) #

- [ ] CUSTOM FIELDS:  Toggle ACT fields on/off in backend 
    As an OS user with the ability to import/export frameworks  
     I want the ability to turn ACT custom fields on/off in the CASE file  
     So that we can decide whether they should be included/excluded values in our framework
    
    **SCOPE**  
     The scope of this story is to have the ability to turn the ACT custom fields on/off on the backend.  This functionality will be called 'ACT-CF' as an option.  This will allow system admins to determine whether the ACT custom fields should be included/excluded with the CASE file when a framework is imported/exported from OpenSALT.
    
    **OUT OF SCOPE**  
     Adding the Task Model entity/schema will be completed with KMS-4422  
     Adding the ACT Custom Fields to the DB will be completed with KMS-4306  
     Adding the Universal Order will be completed with KMS-4431  
    Creating a tabbed Item Editor UI will be completed with KMS-4314  
     Adding the new tab on Import Framework will be completed with KMS-4322  
     Error messaging will be completed with KMS-4330  
     Backend capability to support custom fields will be completed with KMS-4338  
     Updating the Exporter to support custom fields will be completed with KMS-4346  
     Migration of existing data will be completed with KMS-4399  
       
    **AUTOMATED ACCEPTANCE TEST CASES**  
     Confirm parameter.yml is updated with on/off toggle?
    
    **DOMAIN**  
     parameters.yml
    
    **DOCUMENTATION**  
     [https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit#](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit)
    
- [ ] CUSTOM FIELDS:  Create ACT Custom Fields in DB
    As a OS user with the ability to import/export frameworks  
     I want the ACT Custom Fields added to the DB  
     So that we can use them in our framework
    
    **SCOPE**  
     The scope of this story is to update the DB to include the ACT custom fields in the DB.  The list of custom fields include:
    
    1. Item Taxonomy Codes?  Need Brandon to confirm
    2. Statement Origin
    3. Citations Text
    4. Reporting Categories
    
    **OUT OF SCOPE**  
     Adding the Task Model entity/schema will be completed with KMS-4422  
    Adding the Universal Order will be completed with KMS-4431  
     Ability to toggle ACT-CF on/off will be completed with KMS-4298  
     Creating a tabbed Item Editor UI will be completed with KMS-4314  
     Adding the new tab on Import Framework will be completed with KMS-4322  
     Error messaging will be completed with KMS-4330  
     Backend capability to support custom fields will be completed with KMS-4338  
     Updating the Exporter to support custom fields will be completed with KMS-4346  
     Migration of existing data will be completed with KMS-4399
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
    <need input from team>
    
    **DOMAIN**  
    OS DB > Table/fieldnames?
    
    **DOCUMENTATION**
    
    Joe's list of custom fields:  [https://docs.google.com/spreadsheets/d/1kjve-MlAchTFUj\_hGsmuYRJG0yG8FGsCrKvKwRDiPGk/edit?invite=CNfD890H&ts=5b17f2ad#gid=0](https://docs.google.com/spreadsheets/d/1kjve-MlAchTFUj_hGsmuYRJG0yG8FGsCrKvKwRDiPGk/edit?invite=CNfD890H&ts=5b17f2ad#gid=0)
    
    [https://docs.google.com/spreadsheets/d/1QPaNTcA3na36UmusaTilVp17xkIdJTAXZ1Siisrs0lE/edit#gid=582306884](https://docs.google.com/spreadsheets/d/1QPaNTcA3na36UmusaTilVp17xkIdJTAXZ1Siisrs0lE/edit#gid=582306884)
    
    [https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit#](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit)
    
- [ ] CUSTOM FIELDS:  Update backend to read ACT-CF CASE
    As an OS user with the ability to import/export frameworks  
     I want Export Framework backend updated  
     So that we can export by ACT-CF and include the ACT custom fields
    
    **SCOPE**  
     The scope of this story is update the backend to read ACT-CF CASE to allow users to export an ACT-CF Framework successfully. 
    
    **OUT OF SCOPE**  
    Adding the Task Model entity/schema will be completed with KMS-4422  
     Adding the ACT Custom Fields to the DB will be completed with KMS-4306  
     Adding the Universal Order will be completed with KMS-4431  
     Ability to toggle ACT-CF on/off will be completed with KMS-4298  
     Creating a tabbed Item Editor UI will be completed with KMS-4314  
     Adding the new tab on Import Framework will be completed with KMS-4322  
     Error messaging will be completed with KMS-4330  
    Updating the Exporter to support custom fields will be completed with KMS-4346  
     Migration of existing data will be completed with KMS-4399
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
     <need input from team>
    
    **DOMAIN**  
    OS Landing Page > Select a Framework > Select 'Export' button  
      
      
    **DOCUMENTATION**  
     [https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit#](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit)
    
- [ ] CUSTOM FIELDS:  Update Exporter to allow ACT-CF CASE to be exported
    As an OS user with the ability to import/export frameworks  
     I want Export Framework backend updated  
     So that we can export by ACT-CF and include the ACT custom fields
    
    **SCOPE**  
     The scope of this story is update the backend to read ACT-CF CASE to allow users to export an ACT-CF Framework successfully. 
    
    **OUT OF SCOPE**  
    Adding the Task Model entity/schema will be completed with KMS-4422  
     Adding the ACT Custom Fields to the DB will be completed with KMS-4306  
     Adding the Universal Order will be completed with KMS-4431  
     Ability to toggle ACT-CF on/off will be completed with KMS-4298  
     Creating a tabbed Item Editor UI will be completed with KMS-4314  
     Adding the new tab on Import Framework will be completed with KMS-4322  
     Error messaging will be completed with KMS-4330  
     Backend capability to support custom fields will be completed with KMS-4338  
    Migration of existing data will be completed with KMS-4399
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
     <need input from team>
    
    **DOMAIN**  
    OS Landing Page > Select a Framework > Select 'Export' button  
      
      
    **DOCUMENTATION**  
     [https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit#](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit)
    
- [ ] CUSTOM FIELDS:  Create Task Model DB Entity/Schema
    As a OS user with the ability to import/export frameworks  
     I want the DB updated to include the Task Model entity/schema  
     So that we can use them to attach to items
    
    **SCOPE**  
     The scope of this story is to update the DB to allow task models to be added, edited, and deleted.  Code will generate a new db table (task models) we should be able to CRUD on the task models.  CFItems will be associated to a task model.  Assumption is that an item can only have one task model and the task model will only be assigned to a single item.
    
    **OUT OF SCOPE**  
     Adding the ACT Custom Fields to the DB will be completed with KMS-4306  
     Adding the Universal Order will be completed with KMS-4431  
     Ability to toggle ACT-CF on/off will be completed with KMS-4298  
     Creating a tabbed Item Editor UI will be completed with KMS-4314  
     Adding the new tab on Import Framework will be completed with KMS-4322  
     Error messaging will be completed with KMS-4330  
     Backend capability to support custom fields will be completed with KMS-4338  
     Updating the Exporter to support custom fields will be completed with KMS-4346  
     Migration of existing data will be completed with KMS-4399
    
    **AUTOMATED ACCEPTANCE TEST CASES**
    
    1. Precursor:  May need to add forms to the UI
    2. Create task model
    3. Edit task model
    4. Delete task model
    
    **DOMAIN**  
    OS DB > Task\_Models
    
    **DOCUMENTATION**
    
    Joe's list of custom fields:  [https://docs.google.com/spreadsheets/d/1kjve-MlAchTFUj\_hGsmuYRJG0yG8FGsCrKvKwRDiPGk/edit?invite=CNfD890H&ts=5b17f2ad#gid=0](https://docs.google.com/spreadsheets/d/1kjve-MlAchTFUj_hGsmuYRJG0yG8FGsCrKvKwRDiPGk/edit?invite=CNfD890H&ts=5b17f2ad#gid=0)
    
    [https://docs.google.com/spreadsheets/d/1QPaNTcA3na36UmusaTilVp17xkIdJTAXZ1Siisrs0lE/edit#gid=582306884](https://docs.google.com/spreadsheets/d/1QPaNTcA3na36UmusaTilVp17xkIdJTAXZ1Siisrs0lE/edit#gid=582306884)
    
    [https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit#](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit)
    
- [ ] CUSTOM FIELDS:  Universal Order functionality
    As a OS user with the ability to import/export frameworks  
     I want the ability to add a Universal Order to my statements/sub-statements  
     So that I view them in order and can re-order them, as needed
    
    **SCOPE**  
     The scope of this story is to update OS to allow Universal Order to be applied to statements and sub-statements.  For Example:
    
    | Description | Universal   
     Order |
    | --- | --- |
    | Statement 1 | 1 |
    |      Sub-statement 1 | 2 |
    |      Sub-statement 2 | 3 |
    | Statement 2 | 4 |
    |      Sub-statement 1 | 5 |
    |      Sub-statement 2 | 6 |
    |      Sub-statement 3 | 7 |
    
     
    
     
    
    **OUT OF SCOPE**  
     Adding the Task Model will be completed with KMS-4422  
     Ability to toggle ACT-CF on/off will be completed with KMS-4298  
    Adding the ACT Customer fields to the DB will be completed with KMS-4306  
     Creating a tabbed Item Editor UI will be completed with KMS-4314  
     Adding the new tab on Import Framework will be completed with KMS-4322  
     Error messaging will be completed with KMS-4330  
     Backend capability to support custom fields will be completed with KMS-4338  
     Updating the Exporter to support custom fields will be completed with KMS-4346  
     Migration of existing data will be completed with KMS-4399
    
    **AUTOMATED ACCEPTANCE TEST CASES**  
    <need input from team>
    
    **DOMAIN**  
    OS DB > Table/fieldnames?
    
    **DOCUMENTATION**
    
    Joe's list of custom fields:  [https://docs.google.com/spreadsheets/d/1kjve-MlAchTFUj\_hGsmuYRJG0yG8FGsCrKvKwRDiPGk/edit?invite=CNfD890H&ts=5b17f2ad#gid=0](https://docs.google.com/spreadsheets/d/1kjve-MlAchTFUj_hGsmuYRJG0yG8FGsCrKvKwRDiPGk/edit?invite=CNfD890H&ts=5b17f2ad#gid=0)
    
    [https://docs.google.com/spreadsheets/d/1QPaNTcA3na36UmusaTilVp17xkIdJTAXZ1Siisrs0lE/edit#gid=582306884](https://docs.google.com/spreadsheets/d/1QPaNTcA3na36UmusaTilVp17xkIdJTAXZ1Siisrs0lE/edit#gid=582306884)
    
    [https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH\_JHtlVyWbF7tbABpxDc/edit#](https://docs.google.com/document/d/1jPk9ncQqQRD-MqLDBwRADWwH_JHtlVyWbF7tbABpxDc/edit)
    

custom ACT fields.xlsx (https://act.aha.io/attachments/6537342042452722898/token/08f527244af11ca528f70bda6e46da962385974d799a177218f366473cf509c5.download?size=original)

Created from Aha! https://act.aha.io/features/ACKM-307

**Comment by roverwolf** [comment]
Related to #504 ?

**Comment by brandonopened** [comment]
Yeah, these are those stories. One question for you dave is what did we/should we call the toggle for additional fields here. 'custom' ?

**Comment by roverwolf** [comment]
@brandonopened I'd think we want something more specfic than "custom", maybe "task_model_fields" or something like that?

**Comment by jmarks** [comment]
I am unclear on the scope and extensibility of the custom field(s), can we discuss the re-usability of this custom extension? Also the On/Off behavior? If we are creating an approach for custom data extension, we will want to make it more general use. For example, we have an internal desire to add an annotation to an association. Is there a common need here in any way. Let's discuss before a design for this is finalized.

**Comment by brandonopened** [comment]
Each CF document has an extra DB field that allows for a json insertion. This already exists. Perhaps the 'on' switch would turn on the display of that field for each element
example:
CFDoc: Add template information to the CF Document
CfItem: Custom fields for the CF Item to facilitate the above
CFAssociation: Facilitate Annotations of Associations.  

@JosephLeon can you help catch up on what we had decided for our approach?

**Comment by jmarks** [comment]
As we discussed this morning, anyone can create a data extension to any of the three main CASE objects, CFDoc, CFItem and CFAssociation, and that extension is stored as a JSON field associated with each of the these records. In the build process you configure an extension 'on' which defines that UI presentation for creating and displaying an extension.

What we did not discuss this morning is if any of those extensions are available via an API.

**Comment by roverwolf** [comment]
@jmarks More specifically:
  1) Data can be added to the `extra` JSON field that is part of each of the entities
  2) In the **deployment configuration** environment variables one can enable the **feature** that enables the UI presentation
