### ISSUE TITLE
Error with Update Spreadsheet sorting

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#554]
As an editor, when I download a framework as a spreadsheet and the update it, the order of statements is incorrect.  Opensalt v2.1 . 

http://frameworks-staging.act.org/cftree/doc/750 

downloaded spreadsheets before (spreadsheet sort.xlsx) and after update framework (spreadsheet sort(1).xlsx) with screenshots. Note that SmartLevel values are intact, so something with the UI perhaps and no SequenceNumber. 

Suggested remediation:
Incorporate SequenceNumber into Spreadsheet export. This would also help the CfItem sheet be directly compatible with the CSV loader. 

<img width="330" alt="framework sort before" src="https://user-images.githubusercontent.com/14943151/42836774-d1f943ea-89b0-11e8-8b44-afab218cb930.png">

[Spreadsheet_Sort (1).xlsx](https://github.com/opensalt/opensalt/files/2202791/Spreadsheet_Sort.1.xlsx)

<img width="242" alt="framework after update" src="https://user-images.githubusercontent.com/14943151/42836775-d26532d0-89b0-11e8-988e-93f47e9ba6ba.png">

[Spreadsheet_Sort.xlsx](https://github.com/opensalt/opensalt/files/2202792/Spreadsheet_Sort.xlsx)

**Comment by roverwolf** [comment]
How did the framework get created in the first place?  Did the associations have sequence numbers then, or only after the framework was updated from the spreadsheet?

Having both sequence numbers (on associations) and smart level (on items) could make things confusing?  Which is correct?  What if they do not match?

**Comment by brandonopened** [comment]
I created the framework in opensalt. You're right there aren't sequence numbers downloaded in the template only smart levels - which remain intact. So perhaps something with the UI not reading smartlevels correctly.

**Comment by roverwolf** [comment]
Smart levels are generated in the process of creating the spreadsheet, so they do not exist for the UI to read/use.

I'm thinking that there are no sequence numbers being set when the items were first created, or the spreadsheet export is not correctly picking them up for some reason.

**Comment by roverwolf** [comment]
A fix would be to add a sequence number to the association when a child association is added.

This would mean that any new children added would show up at the top of the list when there are older children that do not have a sequence number.  Re-ordering after that would fix the ordering going forward (adds sequence numbers to all the siblings being reordered).

**Comment by roverwolf** [comment]
Yes, for any children added after the fix went in.
