### ISSUE TITLE
Format SmartLevel on download spreadsheet

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#559]
As an editor of OpenSALT, I want to download a spreadsheet and have the CfItems displayed in the same manner as the UI - by Smartlevel. 

The rows of the spreadsheet should parse by SmartLevel in the same way the UI does. (currently it is sorted from oldest to newest)

**Comment by roverwolf** [comment]
Fixed by #595 for any items that have been added after that change is deployed (as mentioned in #554)
