### ISSUE TITLE
Create association to external framework broken with error message

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#560]
In OpenSALT 2.1, create an association to an eternal framework by loading an external framework and then dragging one item form the external fromework on the right to the left tree view for the active framework on the left. Upcon clicking "Associate" on the association dialog box, you see an error and no association is created:

![image](https://user-images.githubusercontent.com/1319413/43106261-cb5f82d4-8e8c-11e8-9230-d3410daaa9fc.png)

**Comment by jmarks** [comment]
We need some sort of automated unit test for this feature.

**Comment by brandonopened** [comment]
Copy from external server doesn't work either. I tried this framework: https://case.georgiastandards.org/uri/23a8e45a-9d5a-11e7-81bc-064e21a83c7c

**Comment by jmarks** [comment]
Note the feature work in 2.0, and is broken in 2.1
