### ISSUE TITLE
Change the way the URI is displayed and linked in the item detail panel

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#563]
The item detail has the "CASE Framework URI" with a link. However this is the OpenSALT URI not the CASE URI, but both are useful. Instead display just the UUID as the "Identifier" and have it link to the CASE URI so you can copy the CASE URI.

**Comment by roverwolf** [comment]
@jmarks Note that the "CASE URI" is not required by the spec to be a URL to the CASE API endpoint.

**Comment by brandonopened** [comment]
So, with #578 our item detail changed a bit! 
We just need to add CASEItemGUID underneath it. Will help with implementation/demo for LTI Resource Search etc.

**Comment by brandonopened** [comment]
Ok, it looks like we would add it here:
  for (key in attributes = {
                'uri': 'CASE Item URI',
                'le': 'List Enumeration in Source',
                'cku': 'Concept Keywords URI',
                'lang': 'Language',
                'licenceUri': 'Licence URI',
                'mod': 'Last Changed'

on opensalt/assets/js/cftree/view-documentclass.js ? 

I tried locally adding in identifier, UUID, and GUID but they didn't work. Probably is something that we would need to change in two places plus add a test.

**Comment by brandonopened** [comment]
What I want to see is the identifier alone like on the LSDoc index page. that uses this variable: lsDoc.identifier but i don't see where to put it on the CfTree item view.

**Comment by jmarks** [comment]
Update on design for this:
Display should include two lines:
Identifier:  UUID as a number that can be copied
URI: the actual URI with a hyperlink. 

[Perhaps the UUID could be a hyperlink to the URI to do this in a single line]

**Comment by brandonopened** [comment]
Dev branch looks like this:
<img width="587" alt="screen shot 2018-11-27 at 2 37 59 pm" src="https://user-images.githubusercontent.com/14943151/49116408-498cbb80-f252-11e8-9024-5921d330a468.png">
<img width="638" alt="screen shot 2018-11-27 at 2 37 55 pm" src="https://user-images.githubusercontent.com/14943151/49116409-498cbb80-f252-11e8-9380-a2ee058414c2.png">



However, when I load a CASE framework from an external source, it correctly has a local URI throughout the framework that works with the API. 
<img width="826" alt="screen shot 2018-11-27 at 2 39 27 pm" src="https://user-images.githubusercontent.com/14943151/49116415-4db8d900-f252-11e8-8369-1f25108ec37b.png">

It seems just the UI adds the prefix. I suggest we just drop the hyperlink part for the framework URI.

**Comment by brandonopened** [comment]
well that example doesn't show a framework that was loaded from an external source where I believe the main conflict lies because then it creates a URI that is (local server)(CASE source URI)

**Comment by brandonopened** [comment]
Ok, with #676 I think we can finally close this ticket for good. And get this in 2.2

**Comment by roverwolf** [comment]
Closing with #676
