### ISSUE TITLE
Import Children Button Does not work

### ISSUE THREAD

**Issue by atg22896** [opensalt/opensalt#564]
When attempting to upload a CSV file to import children, when the button is clicked nothing happens. Unlike this video: https://www.youtube.com/watch?v=7YJAsjZ8BjQ I do not get the next screen when the import button is pressed. No error messages or anything

**Comment by brandonopened** [comment]
hi Alex, a few questions:
1) What version of OpenSALT? Straight from github here or a previously published version?
2) Make sure your file is a CSV. 
3) Once you've tried to import it, is there an Import Logs button? 
![importlogs](https://user-images.githubusercontent.com/14943151/43627573-793f25f6-96e6-11e8-97f7-799481cb4a46.PNG)

4) In the same vein, is there anything recorded on the Log View tab? 
![views](https://user-images.githubusercontent.com/14943151/43627645-b3eab51c-96e6-11e8-93d8-393aca0c1a22.PNG)


Let me know and I'd be happy to schedule a 1:1 with you once we've verified this information! Thanks.

**Comment by atg22896** [comment]
1. Straight from Github
2. File is a CSV. Tried the sample in sample files, and a minimum based from the template
3. No import logs button.
4. Only thing in log view tab is the framework added. 

When clicking the button, the link changes from http://127.0.0.1:3000/cftree/doc/1 to http://127.0.0.1:3000/cftree/doc/1#, but it still stays on the same page. I also noticed I have no import from github button.
![2018-08-06-114238_1920x950_scrot](https://user-images.githubusercontent.com/33287665/43726767-06033156-996e-11e8-922c-d103f435b240.png)

**Comment by atg22896** [comment]
I just tried importing the CASE file for framework, and it also does not work. It's always possible it could be the virtual machine that's causing it to be wonky. I will try installing it locally on a dual boot partition rather than a VM.

**Comment by roverwolf** [comment]
@atg22896 Do you see any errors in the phpfpm container logs?
If you turn on debugging and use `http://127.0.0.1:3000/app_dev.php` do you see any errors in the symfony webprofiler?

**Comment by roverwolf** [comment]
@atg22896 Are you still seeing this issue?

**Comment by atg22896** [comment]
@roverwolf it was a VM issue. When installing to a local OS it worked fine.
