### ISSUE TITLE
reCAPTCHA dependency

### ISSUE THREAD

**Issue by rowan-m** [opensalt/opensalt#565]
### Describe the solution you'd like
You have `google/recaptcha` as a dependency. I've recently updated this with a `1.2` release. It *should* be backwards compatible, but obviously you'd want to test that. Happy to respond to issues over at https://github.com/google/recaptcha

**Comment by brandonopened** [comment]
Dave, currently owners of the recaptcha keys are myself and Josh... can we add you as well? I'll coordinate offline for an email address.

**Comment by roverwolf** [comment]
Updated reCAPTCHA library in PR #566
