### ISSUE TITLE
CASE Format URL does not work on imported Frameworks

### ISSUE THREAD

**Issue by jonscheiding** [opensalt/opensalt#568]
### Describe the problem
The "CASE Format URL" link doesn't work in Frameworks that were created by importing a CASE file.

### Version of OpenSALT
2.1.0

### To reproduce
1. Select Import Framework
2. Select and import either of the CASE files in the attached ZIP
3. Click on the newly imported Framework
4. In the Item Details pane, click the CASE Format URL link

[case-format-examples.zip](https://github.com/opensalt/opensalt/files/2271279/case-format-examples.zip)

### Expected behaviour
The link should redirect you to the imported framework in your OpenSALT instance.

### Actual behaviour
You receive an error "Could not find the Uri: <identifier>"

### Your system (please complete the following information):
 - Device: desktop
 - OS: multiple
 - Browser: multiple

### Additional context

Related: #471, #563

Database results from my import (showing how this issue happens even when there are no URI's in the CASE file):

```
select  id, uri, identifier, title 
from    ls_doc 
where   identifier in ('6635643b-6c2f-4a28-9713-f52190b28ff9', '4be8c04b-ce77-4b6a-8084-f28a3c1d010a');
```

| id | uri                                                                     | identifier                           | title                                            |
|----|-------------------------------------------------------------------------|--------------------------------------|--------------------------------------------------|
|  7 | https://www.testframeworks.org/doc/6635643b-6c2f-4a28-9713-f52190b28ff9 | 6635643b-6c2f-4a28-9713-f52190b28ff9 | Test Framework with Imported URIs                |
| 11 | local:285619f8-9b26-11e8-96b7-0242ac1a0003                              | 4be8c04b-ce77-4b6a-8084-f28a3c1d010a | Test Framework Without Imported URIs             |

**Comment by jonscheiding** [comment]
I'd be happy to submit a PR, provided I understand the expected behavior.  Are any of the following accurate expectations?

1. Links like `http://localhost:3000/uri/<identifier>` should always work, so long as there is a record with that identifier.
2. A `local:` URI generated when importing CASE files should match the record's identifier in the CASE file, if there is one.

**Comment by jmarks** [comment]
On #2) Indeed, we have two import stories to differentiate: import as a existing framework unchanged (Copy), import and create a new derivative framework.

**Comment by roverwolf** [comment]
Yes, in OpenSALT we are using the identifier as the unique part of the local URI.

**Comment by jonscheiding** [comment]
Thanks!  Based on your responses I opened a couple of minor PRs on this issue.  I can add some acceptance tests if you like, just wanted to get them in front of you for feedback.
