### ISSUE TITLE
Excel export does not use sequenceNumber to order items and their smartLevel

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#597]
When generating the `smartLevel` value, the `ExcelExport` class does not consider the *isChildOf* association's `sequenceNumber` to determine the order and smartLevel of the items.

#### Some related background

This issue is observed elsewhere as well, `sequenceNumber` was introduced into the spec quite late and the code has never been fully updated to use it (as it can be difficult at times due to the value not being easily obtained for an item).

Before the sequenceNumber field existed a `rank` field was added for internal use to allow for ordering items among siblings within OpenSALT.  At this point, many areas of the code do not try to use or update the rank field due to (I am assuming) the sequenceNumber being the correct way to handle sibling order.  The rank field should probably be removed.

When displaying items there is also an attempt to order by `listEnumInSource` and `humanCodingScheme` if there is no specified order.

**Comment by brandonopened** [comment]
@JorgeLu1s is working on something related to this; we want to add SequenceNumber to the exporter and importer. If SequenceNumber is present the UI should read that before SmartLevel. 
- we should probably deprecate ListEnumInSource (seems somewhat useless anyway?) and leave HumanCoding scheme only as a last resort...

**Comment by roverwolf** [comment]
One this issue is resolved, yes, `smartLevel` should be generated based on the isChildOf relationships.

Note that `smartLevel` is not a stored field, it is *only* used with the export/import.

I agree that `listEnumInSource` should be removed from the ordering calculation, in many cases it is just  a bullet.  We might also remove humanCodingScheme from the ordering calculation and only use sequenceNumber... Where items without a sequenceNumber would then be considered unordered in the UI (but would get a random order when generating an export).

We would need to figure out how to migrate the data and add sequenceNumber to all the isChildOf relationships.

There is a question about what we should do if external CASE files do not include a sequenceNumber (as it is optional).

Another wrench for the overall ordering issue is that the JS UI has been changed over time but the same changes were not made to the HTML output that is initially generated.  Should we (longer term) move to only having a full SPA JS frontend and remove the HTML page that is currently generated?

**Comment by brandonopened** [comment]
@JorgeLu1s this is needing a bigger discussion and actual examples.

**Comment by brandonopened** [comment]
Preferred Sort order: 
SequenceNumber . If no Sequence Number on row 1 go to SmartLevel
if No smartLevel go to Human Coding Scheme (alphabetical) 

Use Case 1: Document has Sequence Number 
Result: Sequence Number created/used on Import (just as happens with CSV importer currently). 

Use Case 2: Document has SequenceNumber and SmartLevel
- Use SequenceNumber
Potential issue: When a user is using Spreadsheet Updater to add a new statement, there will not be a sequence Number present. 

Use Case 3: No sequenceNumber or SmartLevel
Sort each level of hierarchy by HumanCodingScheme (currently is alphabetical)

**Comment by roverwolf** [comment]
In the Excel export **CFItems** sheet there should be no need for a `sequenceNumber`.

The `smartLevel` (ex. **2.3**.*5*) is intended to relay 3 things:
- It identifies the parent of the item (**2.3**)
- It designates its order among the parent's children (*5*)
- It provides an identifier for its children to refer to (via their smartLevel, ex **2.3**.*5*.2)

Having both a `smartLevel` and `sequenceNumber` in the **CFItems** sheet would just confuse things., and if there is no `smartLevel` then we cannot determine the parent item (so would end up being a top-level item of the document).

The **CFAssociations** sheet should contain a `sequenceNumber` to be used with non `isChildOf` associations so that they can also have a sequence.

**Comment by brandonopened** [comment]
Great, keeping things CASE compliant too...
<img width="647" alt="screen shot 2018-08-30 at 7 44 09 am" src="https://user-images.githubusercontent.com/14943151/44859252-9ac3e980-ac28-11e8-95cd-34f376ce8368.png">

**Comment by brandonopened** [comment]
Closed #600
