### ISSUE TITLE
Allow customizing colors and base template

### ISSUE THREAD

**Issue by jonscheiding** [opensalt/opensalt#604]
### Feature story
```
Feature: <feature name>
  As an implementor of Standards Connect
  I want to be able to customize colors and layout of the site
  So that I can enhance it with my own branding identity.
```

### Describe the solution you'd like
Two main extension points:

- Placeholders for custom SASS variables and styles
- Ability to override the `base.html.twig` template

PR forthcoming.

**Comment by brandonopened** [comment]
I am late and I see the PR but is this adding specific colors or just the ability to change the base css template. Eg I could make it ACT blue on my OpenSALT instances?

**Comment by roverwolf** [comment]
It makes it easier to specify many of the colours using a variables file
that will be loaded by SASS when building the css.
