### ISSUE TITLE
Filtering the subject list doesn't work

### ISSUE THREAD

**Issue by gmenyhert** [opensalt/opensalt#610]
### Describe the problem
The "Subjects" field on the "Edit Document" screen looks to support filtering but it doesn't work.

### Version of OpenSALT
2.1.0

### To reproduce
When you click in the field, the drop down reads "Searching".  When you type a character, it refreshes the list.  However, nothing actually changes in the list and nothing is filtered.  Type "Sci" and you still get every subject in the list.

### Expected behaviour
Typing in the Subjects field filters the list of subjects to only those that match your entry.

### Actual behaviour
The list blinks like it is refreshing but nothing changes.

### Screenshots
![opensalt subject filter](https://user-images.githubusercontent.com/23660702/45883828-2b9d6900-bd80-11e8-943b-a8739808a803.png)

### Your system (please complete the following information):
 - Device: desktop
 - OS: Windows 10
 - Browser: chrome

**Comment by roverwolf** [comment]
Thank you for reporting this issue.  This missing functionality should be part of the next release.
