### ISSUE TITLE
Association to External server needs full URI

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#634]
Currently, when I make an association to an external server, only the identifier is recorded in the  json output. 

As an editor, when I make an association to a CfItem on an external server, the entire URI should be recorded for the destinationURI field. 

example use case: 

http://frameworks-staging.act.org/cftree/item/153270
has an association to an external item http://frameworks.act.org/ims/case/v1p0/CFItems/be5a888d-559a-4779-96b3-19765981a050  BUT in the json output I only see the identifier, so this would not be retained if exported to a different server

{"title":"Destination Node","identifier":"be5a888d-559a-4779-96b3-19765981a050","uri":"be5a888d-559a-4779-96b3-19765981a050"}}]

**Comment by roverwolf** [comment]
Should probably just be part of 2.2, we should get that train moving soon.
