### ISSUE TITLE
Exporting a PDF for a larger framework fails

### ISSUE THREAD

**Issue by roverwolf** [opensalt/opensalt#635]
### Describe the problem
When using the "Styled PDF" export of a framework it ends up giving a blank document if the framework is not small.

### Version of OpenSALT
2.1+

### To reproduce
Steps to reproduce the behaviour:
1. Go to a largish framework
2. Click on "Export"
3. Click "Styled PDF"
4. Download the genereated PDF
5. The PDF is empty

### Expected behaviour
One expects the PDF to contain the framework information.

### Actual behaviour
The downloaded PDF is empty.

### Additional context
It appears that PHP runs out of memory when generating the PDF.

**Comment by roverwolf** [comment]
Let's hide the button for now until the memory issues are resolved (or alternative determined).

**Comment by brandonopened** [comment]
Agreed, this was pointed out by our PR team last week so was going to suggest we do it. The PDF's look pretty good now when images and lost of associations are there... but yeah for large/important frameworks it fails.

**Comment by jmarks** [comment]
#637 added, you can now close this one.
