### ISSUE TITLE
Updating Framework creates duplicate child items each time

### ISSUE THREAD

**Issue by sarellat** [opensalt/opensalt#657]
As an OS editor, when I make both internal and external associations onto a framework then export the framework and update the framework with the spreadsheet creates  duplicate child items in the framework. Also, the associations made in the spreadsheet only retained in case of Is Related To and Exact Match Of i.e if we replace Is Related To with Exact Match Of or vice versa, the changes are reflected on UI from spreadsheet updater, other changes in association type are not reflected.

Steps to reproduce the behaviour:
1.Login into OS app as an editor
2.Crate a new framework with at least 1 child item
3.Export the framework into a spreadsheet
4.Update the framework by importing the updated spreadsheet.

Expected behavior:
No duplicate child items should be created, updates from spreadsheet should be reflected in the framework on the UI.

Actual behavior:
Duplicate child items created in the framework and all association type changes are not reflected on the UI

branch: https://github.com/opensalt/opensalt/tree/fix/n-level-association

**Comment by roverwolf** [comment]
This should be fixed by #697
