### ISSUE TITLE
Presentation URI is incorrect

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#658]
version: dev

Issue: An imported CASE framework retains the correct URI on the backend, but the frontend UI seems to automatically append the base URI
<img width="1222" alt="screen shot 2018-11-14 at 12 55 24 pm" src="https://user-images.githubusercontent.com/14943151/48502086-b8a6f080-e80c-11e8-9720-991071b0c9c5.png">
<img width="954" alt="screen shot 2018-11-14 at 12 55 12 pm" src="https://user-images.githubusercontent.com/14943151/48502087-b8a6f080-e80c-11e8-911d-013198e40182.png">

**Comment by roverwolf** [comment]
That is the originally intended behaviour, but now mis-labeled and perhaps no longer desired.

The link shown is a link to the UI interface on the site for the item, not the API URI.
