### ISSUE TITLE
Update Framework error troubleshooting

### ISSUE THREAD

**Issue by bhammock54** [opensalt/opensalt#660]
I'm trying to update a framework via an imported spreadsheet and am getting a 500 error.  However, I'm not sure where to find a log file pointing me towards the actual error so I can correct it.  I've poked around in Linux, and through Symfony looking for something but to no avail.  Can anyone point me in the right direction?

**Comment by JorgeLu1s** [comment]
hey @bhammock54 you can check the live logs of the docker image with the command `docker logs -f cftf_phpfpm_1` to get an idea of what is happening.

**Comment by bhammock54** [comment]
Thanks @JorgeLu1s that got me where I needed to be.  I'm new to Docker so learning that as well.  I'll be hitting that page harder to learn my way around now, thanks!

**Comment by JorgeLu1s** [comment]
Glad to hear it worked! I'm closing this issue.
