### ISSUE TITLE
Make Exemplar field clickable

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#669]
Currently an exemplar link is not able to be clicked on. 
As a user browsing a framework, I want to be ale to click on a link in the exemplar field.

**Comment by brandonopened** [comment]
http://frameworks-staging.act.org/cftree/item/311628

ok if I add in the HTML manually it clicks through but the link appears below the Exemplar UI. will refile as bug.

**Comment by roverwolf** [comment]
Refer to #671
