### ISSUE TITLE
Import a CASE file with association groups does not work

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#678]
As a user, if I have a framework with association groups, importing the CASE file does not retain the association groups although it does import all Items. 

Expected behavior would replicate the association groups seen on the UI before export and in the CASE json.

**Comment by jmarks** [comment]
Need to address both spreadsheet and JSON import and export of association groups. Why is this not a CASE conformance issue? Maybe it is?

**Comment by brandonopened** [comment]
If assoc groups are present spreadsheet update (not import) will preserve them. Yes need assoc group creation on import for botb

**Comment by vkaripineni** [comment]
@jmarks @roverwolf  I exported a framework (that I created) that has Association Groups. I then deleted this framework. Using the Import Framework functionality, I imported the framework using the JSON file (that I exported previously). I could not see the Association groups that I created previously. Am I missing something here?

**Comment by roverwolf** [comment]
@vkaripineni Were any associations in the framework in the association groups?  Association groups will only be exported if they are used in the framework.

**Comment by vkaripineni** [comment]
Thank you @roverwolf . I made sure that associations in the framework are in these association groups that I created and it worked.
