### ISSUE TITLE
Adding External Documents is broken with latest Dev update

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#686]
With the change in identifier it seems associate to eternal server is broken. 

Screenshot shows that I have previously added the CCSS ELA standards from within OpenSALT. 
- Upon recent update of the CASE registry code I cannot access this framework from another opensalt server. 
- I tried re-adding it via https://caseregistry.imsglobal.org/case/v1p0/CFPackages/c64961be-d7cb-11e8-824f-0242ac160002.json  as well as 

https://caseregistry.imsglobal.org/c64961be-d7cb-11e8-824f-0242ac160002

also tried: https://caseregistry.imsglobal.org/uri/c64961be-d7cb-11e8-824f-0242ac160002 with and without json 
with no success.

**Comment by roverwolf** [comment]
The screenshot is missing.

What was the URL being used previously?

The first URL shown is missing **/ims** before **/case/v1p0/...** (as in https://caseregistry.imsglobal.org/ims/case/v1p0/CFPackages/c64961be-d7cb-11e8-824f-0242ac160002).

The second is missing **/uri/**, and would be a link to the document, the package URL would be https://caseregistry.imsglobal.org/uri/pc64961be-d7cb-11e8-824f-0242ac160002 (or with .json)

**Comment by brandonopened** [comment]
That was it! Strange that I have to reload the documents, but that can be a feature for another day. Thanks.
