### ISSUE TITLE
./bin/console-real not found

### ISSUE THREAD

**Issue by sameth33** [opensalt/opensalt#74]
I ran the following command for database migration
$ ./bin/console-docker doctrine:migrations:migrate --no-interaction

I can the following message:
/usr/local/bin/docker-php-entrypoint: 9: exec: ./bin/console-real: not found

I can see that /bin/console-real exists.

Any help would be greatly appreciated. - Sam

**Comment by roverwolf** [comment]
It sounds like either the main directory is not getting mounted or there is a permissions issue.

Could you provide the output of `./bin/phpcli ls -la {.,bin}`? That should show contents of the main directory as well as the bin subdirectory (and should match the output that you get from just `ls -la {.,bin}` without `./bin/phpcli`).

**Comment by roverwolf** [comment]
@sameth33 Did you figure out the issue you were having with `./bin/console-real`?

If so, please add a comment for future reference (and the README).

**Comment by roverwolf** [comment]
Closing as this is a question and there has been no response to clairifying questions in 2 weeks.
