### ISSUE TITLE
Allow Association Groups to be created in Adopted Frameworks

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#758]
User Story: As an editor of a framework, I want to be able to add association groups to an adopted framework. 

Pursuant to a CASE spec discussion on Evolving Frameworks, one can add associations to adopted frameworks but currently I cannot add or edit association groups. Perhaps there is a reason for this structurally?

**Comment by brandonopened** [comment]
for kicks I made a branch that would allow this - changed the toggle to be "editorrights" instead of "IsDraftStatus" which seems to satisfy potential use cases (ie allows editor in an organization to add and make associations even to an adopted framework)

Works without errors and the associations persist. however as stated wise to wait for more extensive use cases before this minor feature is submitted. 

<img width="883" alt="Screen Shot 2019-05-28 at 3 51 07 PM" src="https://user-images.githubusercontent.com/14943151/58517544-98af9c80-8160-11e9-8626-3dc34f4bd248.png">

**Comment by jmarks** [comment]
Are you adding this to 2.2?
