### ISSUE TITLE
2.2 Password Decryption

### ISSUE THREAD

**Issue by sw-waterford** [opensalt/opensalt#855]
With the latest version of OpenSALT any newly created user is unable to authenticate and receives "Invalid credentials" even though the user is configured properly and the password is correct. Upon further inspection, it is clear that password hash format is different in the salt_users table.

OpenSALT™ 2.2.0-dev.1988+20190627.1825.ac5dfc84

### To reproduce
Steps to reproduce the behaviour:
Setup docker environment using opensalt/app:2.1.1
Log in as administrator and create a new user
Ensure user is able to authenticate in 2.1.1
Review the hash used in the salt_user table 

Setup docker environment using opensalt/app:2.2
Login as as administrator and create new user
Attempt to authenticate with new user
Review the hash used in the salt_user table compare with user created 2.1.1 note difference in prefix

### Expected behaviour
User created in 2.2 should be able to sign in

### Actual behaviour
User receives "Invalid credentials" even though password and user name are correct.
Note the difference in hash format between old user and new user.

### Your system (please complete the following information):
 - Device: Desktop
 - OS: Mac OS
 - Browser Chrome
 - Version 76

**Comment by jmarks** [comment]
@sw-waterford thank you for the report. Opened a 2.2.1 maintenance release for this as anything else like it in 2.2.

**Comment by sw-waterford** [comment]
I think I may have identified the issue, the migrations database changes did not get run with the image going to latest I noticed the field length was changed on the column. How can I run the migrations directly through docker image?

**Comment by holisticnetworking** [comment]
@sw-waterford Please navigate to the root directory of the OpenSALT installation and run the following:
```
make down; make up
./bin/update.sh
```
After that's complete, have another try logging in. Thanks!

**Comment by sw-waterford** [comment]
After running the doctrine migrations script everything is now working as expected thank you for the support.
