### ISSUE TITLE
Request that the document title in an association be increased to 60

### ISSUE THREAD

**Issue by brandonopened** [opensalt/opensalt#859]
As a user, I want to see a full document title in an association on the Item view page. 

Acceptance Criteria: If there is an associated document with a long title, I want to see 60 characters worth of it.

Example:
http://frameworks.act.org/cftree/item/71350
<img width="537" alt="Screen Shot 2019-08-15 at 9 42 27 PM" src="https://user-images.githubusercontent.com/14943151/63139898-9ca3cb80-bfa5-11e9-88a1-b3086e556c5f.png">

**Comment by brandonopened** [comment]
A few things I tried but coudln't seem to get it:
in /templates/framework/doc_tree/ls_association_component I removed the Span from ls.doc.title:
          ```
  {% if item.humanCodingScheme is not empty %}
                                        <span class="item-humanCodingScheme">{{ item.humanCodingScheme }}</span>
                                    {% endif %}
                                    {% if item.fullStatement != item.humanCodingScheme %}
                                        {{ item.fullStatement }}
                                    {% endif %}
                                    {% if item.lsDoc != viewingItem.lsDoc %}
                                        {{ item.lsDoc.title}}
                                    {% endif %}
                                    {% block end_of_item_a '' %}
```

No effect. 

I also tried changing things in the View Modes document: (commenting out the truncation of the title if it's over 35 characters - changed to 60 then even just commented out the other lines - also no effect. 

```
    // if item comes from another doc, note that
            if (!empty(doc) && typeof(doc) === "object" && doc !== apx.mainDoc) {
                let docTitle = doc.doc.title;
                if (docTitle.length > 70) {
                    docTitle = docTitle.substr(0, 60);
//                    docTitle = docTitle.replace(/\w+$/, "");
//                    docTitle += "…";
                }
                title += ' <span style="color:red">' + docTitle + '</span>';

```
after i did each change I did ./update.sh and then docker down and up. Amateur coder is going to stop trying even for what seems like a really simple thing.

**Comment by roverwolf** [comment]
@brandonopened The JS you listed affects how the document title is shown in the association view.  Similar code exists in view-documentclass.js which is used where the screenshot is showing.

**Comment by brandonopened** [comment]
Thanks! Will adjust. I think 60 is better for more documents (eg on CASE Network - Alaska Department of Education & Early Development is 50 characters... and was a request from one of my most supportive users so I try to throw a bone when I can.
