### ISSUE TITLE
./bin/console-docker doctrine:migrations:migrate --no-interaction no Permission

### ISSUE THREAD

**Issue by chenzhikaida** [opensalt/opensalt#87]
when I exec follow operator 
`[root@izuf62b35n77zalsej709dz opensalt-develop]# ./bin/console-docker 
-bash: ./bin/console-docker: /usr/bin/env: bad interpreter: Permission denied`

i access http://hostip:3000/app_dev.php,display You are not allowed to access this file.

how can i do it?

**Comment by roverwolf** [comment]
From the error, it seems like `/usr/bin/env` is not installed on your system.

You could install it or replace the first line of the `./bin/console-docker` script with the path to `bash` instead.
