### ISSUE TITLE
Advance browser to newly-created framework after cloning.

### ISSUE THREAD

**Issue by holisticnetworking** [opensalt/opensalt#883]
### Is your feature request related to a problem? Please describe.
Currently, when cloning a framework, the UI just returns you to the original framework without any indication that the clone has happened. Better UI experience would send the user directly to the new framework which was cloned from the original and allow the user to edit the details of that framework right away.

### Feature story
```
Feature: Advance browser to newly-created framework after cloning.
  As a user
  I want to see the framework I've just created immediately after cloning it
  So that I can edit the newly-created framework.
```

### Describe the solution you'd like
When the new framework is created, instead of sending the user back to the original framework, the system will forward the browser to the new framework view and automatically bring up the edit window.

### Describe alternatives you've considered
The current system leaves open the possibility that a person, not seeing any visible changes when creating a new framework, will attempt the same operation several times, only to find out that they've created several clones.

### Acceptance criteria
```gherkin
Scenario:  
Given a framework requires cloning
When the clone is complete, the user is brought to the new framework in the Edit Framework modal window.
Then we're good
```

**Comment by roverwolf** [comment]
Resolved by #884
