### ISSUE TITLE
Implement mirroring for an external case server or set of external frameworks.

### ISSUE THREAD

**Issue by jmarks** [opensalt/opensalt#906]
**Primary User Story:** As a Super User, I want to configure an external server to be mirrored, and select all or a subset of frameworks on that server to be mirrored, similarly to the mirroring in the CASE network. The only difference is when adding a new mirror you can enter just the server domain and choose to “Mirror all” or “Pick from list”. If you choose to pick from the list, the system should get the list of all frameworks currently on that server and allow you to check one or many of them to mirror individually. If all is selected, when checking for updates, any new frameworks should be automatically added to the mirrors list.

**User Story:** As a Super User I want remove a mirrored framework, set of frameworks or server.

**User Story:** As a Super User I want the system to check for changes to a mirrored framework on a defined schedule, and automatically update a mirror if a framework has changed.

**User Story:** As a Super User I want to see any error in creating or updating a mirror so that I can correct the error. If during an update there is an error, I want the previous mirror(s) cache to continue in use. 

In order to implement this feature and storied the JSON Import and Export will need to be remediated to fully comply with the CASE specification

**Comment by vkaripineni** [comment]
@jmarks @roverwolf When creating a new mirrored server, after I add the url of the server to mirror, I said No to automatically add frameworks (first screenshot below) but when I Clicked save, I see that all the list of frameworks added and shown under the server I added. (second screenshot below)
Here are the screenshots. I was expecting that I should be able to pick from list as mentioned in the requirement in this ticket? Am I wrong? Was this changed?


![image](https://user-images.githubusercontent.com/32309565/131561407-bfc717a1-8614-46f1-9221-8d2fcd0f8e51.png)

![image](https://user-images.githubusercontent.com/32309565/131561477-d42d02d4-bd44-401e-87fc-cb98cee144e2.png)

**Comment by roverwolf** [comment]
@vkaripineni That is the list.  None of the frameworks shown in your second screenshot are being mirrored (the (-) status).

You cannot just "Start Mirroring" them as there is a framework on the system with the same identifier, thus the "Resovle ID Conflict" button on the right which will allow replacing of the existing framework with the mirrored one if desired.

**Comment by vkaripineni** [comment]
Thanks @roverwolf ! I was able to resolve ID and that started mirroring for that particular item.
I do not see Mirror All option. Where do I see it? Should I have all the frameworks ready for mirroring with no conflicts and then will I See it? Is Mirror All in scope?

**Comment by roverwolf** [comment]
@vkaripineni The "Mirror All" option is the second option listed when adding a server.  It is phrased as "Automatically add frameworks?" and requires a No/Yes answer.

**Comment by vkaripineni** [comment]
@roverwolf The thing is the display of the # of frameworks is same when I select Yes or No while adding the server https://sandbox.opensalt.net/. There are about 100 frameworks for any of these options (Yes/No) selected. So not sure if I am missing anything here or if this is an issue?

**Comment by vkaripineni** [comment]
@roverwolf Perfect. Thanks!
