### ISSUE TITLE
how can i access mysql

### ISSUE THREAD

**Issue by chenzhikaida** [opensalt/opensalt#91]
what is account and password in docker?

**Comment by roverwolf** [comment]
The username and passwords will be whatever you have set in the `docker/.env` file that were passed to the container by `docker-compose`.

https://hub.docker.com/_/percona/ has more information on the docker image used for the database service.

**Comment by roverwolf** [comment]
@chenzhikaida Did you figure out how to access MySQL in the docker container?

**Comment by roverwolf** [comment]
Closing as this is a question and there has been no response to clairifying questions in 2 weeks.
